In [ ]:
import sys
from pathlib import Path

def _find_project_root(start: Path) -> Path:
    for p in (start, *start.parents):
        if (p / ".git").exists():
            return p
    raise RuntimeError("Could not locate project root (no .git found above cwd)")

PROJECT_ROOT = _find_project_root(Path.cwd())
sys.path.insert(0, str(PROJECT_ROOT))

# Unified Model Evaluation Pipeline

This notebook evaluates all saved model families with one pipeline using the Section 9+ evaluation structure from the incremental-monthly SGD notebook.

Key policies implemented:
- Incremental-scaler families use the model-year scaler when evaluating prior years.
- Standard-scaler families use the evaluation-year scaler.
- Feature preparation is routed by model family to the original notebook-style function.
- Each evaluation table is saved immediately and supports resume (existing table files are skipped and loaded).
- Final-model evaluation supports an optional final scaler when a family saves one separately.

In [ ]:
import json
import pickle
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = PROJECT_ROOT
EVAL_DIR = PROJECT_ROOT / 'experiments' / 'evaluation' / 'eval_outputs' / 'unified_eval'
EVAL_DIR.mkdir(parents=True, exist_ok=True)

SPLIT_PATH = ROOT / 'data_split.npz'
if not SPLIT_PATH.exists():
    raise FileNotFoundError(f'Missing split file: {SPLIT_PATH.resolve()}')

split = np.load(SPLIT_PATH)

def _first_existing_key(candidates):
    for key in candidates:
        if key in split.files:
            return key
    return None

train_key = _first_existing_key(['train_pixel_indices', 'train_idx', 'train_indices'])
val_key = _first_existing_key(['val_pixel_indices', 'valid_pixel_indices', 'val_idx', 'val_indices'])
test_key = _first_existing_key(['test_pixel_indices', 'test_idx', 'test_indices'])

if not all([train_key, val_key, test_key]):
    raise KeyError(f'Could not resolve split keys from: {split.files}')

train_pixel_indices = split[train_key]
val_pixel_indices = split[val_key]
test_pixel_indices = split[test_key]

print(f'Loaded splits from {SPLIT_PATH.name}')
print(f'  train: {len(train_pixel_indices):,} | val: {len(val_pixel_indices):,} | test: {len(test_pixel_indices):,}')

# The family registry (which model/scaler/dataset/feature-prep-kind goes with
# which family_id) lives in src/eval/families.py -- moved verbatim, with a
# short_label added to every family. See that module's docstring for why no
# generator replaces the literal, and why short_label subsumes what used to be a
# second, only-partially-covering rename dict in the reporting cell.
from src.eval.families import build_families, open_family_dataset

FAMILIES = build_families(PROJECT_ROOT)

# open_family_dataset (src/eval/families.py) memoizes per dataset_path, which
# matters because 50 families share only 3 zarr files. DATASET_CACHE is the cache
# object it reads and writes; load_family_dataset keeps the notebook's original
# one-argument call shape.
DATASET_CACHE = {}


def load_family_dataset(family_cfg):
    return open_family_dataset(family_cfg, DATASET_CACHE)

print(f'Configured {len(FAMILIES)} model families')

Loaded splits from data_split.npz
  train: 5,597,776 | val: 1,273,437 | test: 1,283,992
Configured 43 model families

In [6]:
# Feature preparation for every model family.
#
# The feature math lives in src/mlp_replay/data.py and the caching/dispatch wrapper
# in src/eval/features.py, so evaluation and training can no longer drift apart.
# This notebook previously carried its own copy of the feature builder, and read the
# baseline family's version by exec-ing it out of SGD Classifier.ipynb at runtime --
# both are gone.
#
# Per-family flags below are unchanged, including the two asymmetries worth knowing:
#   * the baseline family imputes S2 gaps over an expanding window (years <= t),
#     while every other family imputes over all years. That difference predates this
#     refactor; it is preserved here rather than quietly harmonised.
#   * the neighbourhood family sets include_last_year=False.
from src.eval.features import FEATURE_CACHE as _FEATURE_CACHE
from src.eval.features import prepare_features_common

# Cell below reports cache statistics through these names; bind them to the cache's
# own objects so the counters stay live.
FEATURE_CACHE = _FEATURE_CACHE.entries
FEATURE_CACHE_STATS = _FEATURE_CACHE.stats
FEATURE_CACHE_MAX_ENTRIES = _FEATURE_CACHE.max_entries


def prepare_features_prevyears(ds, pixel_indices, year_idx, scaler=None, scaler_mode='auto', family_id=None):
    return prepare_features_common(
        ds=ds,
        pixel_indices=pixel_indices,
        year_idx=year_idx,
        scaler=scaler,
        scaler_mode=scaler_mode,
        include_last_year=True,
        include_monthly=False,
        include_neighbourhood=False,
        family_id=family_id,
    )


def prepare_features_baseline_notebook(ds, pixel_indices, year_idx, scaler=None, scaler_mode='auto', family_id=None):
    """Baseline family: no lag features, no monthly indices, expanding-window imputation.

    Named for the era when this function was read out of SGD Classifier.ipynb by
    exec-ing the notebook JSON. It is a normal call now; the name is kept because
    the family configs reference it.
    """
    _ = family_id
    if scaler_mode not in {'auto', 'fit', 'transform'}:
        raise ValueError(
            "baseline_notebook prep only supports scaler_mode values 'auto', 'fit', and 'transform'."
        )
    if scaler_mode == 'transform' and scaler is None:
        raise ValueError("A fitted scaler is required for baseline_notebook with scaler_mode='transform'.")

    return prepare_features_common(
        ds=ds,
        pixel_indices=pixel_indices,
        year_idx=year_idx,
        scaler=None if scaler_mode == 'fit' else scaler,
        scaler_mode=scaler_mode,
        include_last_year=False,
        include_monthly=False,
        include_neighbourhood=False,
        family_id=None,
        impute_window='expanding',
    )


def prepare_features_monthly(ds, pixel_indices, year_idx, scaler=None, scaler_mode='auto', family_id=None):
    return prepare_features_common(
        ds=ds,
        pixel_indices=pixel_indices,
        year_idx=year_idx,
        scaler=scaler,
        scaler_mode=scaler_mode,
        include_last_year=True,
        include_monthly=True,
        include_neighbourhood=False,
        family_id=family_id,
    )


def prepare_features_neighbourhood(ds, pixel_indices, year_idx, scaler=None, scaler_mode='auto', family_id=None):
    return prepare_features_common(
        ds=ds,
        pixel_indices=pixel_indices,
        year_idx=year_idx,
        scaler=scaler,
        scaler_mode=scaler_mode,
        include_last_year=False,
        include_monthly=False,
        include_neighbourhood=True,
        family_id=family_id,
    )


PREP_FN_BY_KIND = {
    'baseline_notebook': prepare_features_baseline_notebook,
    'prevyears': prepare_features_prevyears,
    'monthly': prepare_features_monthly,
    'neighbourhood': prepare_features_neighbourhood,
}


# Scoring metrics and threshold selection live in src/eval/metrics.py -- moved
# verbatim. best_f1_threshold stays a separate implementation from
# src/thresholds.py on purpose (see that module's docstring); both are preserved
# there now instead of only in this cell.
from src.eval.metrics import best_f1_threshold, compute_metrics

# Table read/write lives in src/eval/tables.py. The JSON twins there carry no
# timestamp, so re-running the pipeline no longer rewrites every tracked JSON with a
# one-line diff -- git status is now a real signal about whether a run had side effects.
from src.eval.tables import load_or_run_table, save_table

print('Feature preparation and helper functions loaded')

Feature preparation and helper functions loaded

In [ ]:
# Model/scaler loading and feature-count validation live in src/eval/artifacts.py --
# pure functions, no free globals, moved verbatim.
from src.eval.artifacts import (
    infer_years_from_models,
    load_final_scaler,
    load_model,
    load_scaler,
    resolve_scaler_year,
    validate_feature_count,
    validate_model_features,
    validate_scaler_features,
)


def compute_threshold_for_pair(model_obj, prep_fn, ds, family_cfg, model_year, eval_year, scaler_obj, rbf_sampler=None, default_threshold=0.5, family_id=None):
    year_to_idx = {int(y): i for i, y in enumerate(ds.year.values)}
    eval_year_idx = year_to_idx[int(eval_year)]
    if scaler_obj is None:
        val_scale_mode = 'none'
    else:
        val_scale_mode = 'transform'

    X_val, y_val, _ = prep_fn(
        ds,
        val_pixel_indices,
        eval_year_idx,
        scaler=scaler_obj,
        scaler_mode=val_scale_mode,
        family_id=family_id,
    )
    if len(X_val) == 0:
        return float(default_threshold), {'source': 'fallback', 'reason': 'empty validation set', 'n_val_samples': 0}

    validate_scaler_features(X_val, scaler_obj, family_cfg['label'], model_year, eval_year, 'validation')

    if rbf_sampler is not None:
        X_val = rbf_sampler.transform(X_val)

    validate_model_features(X_val, model_obj, family_cfg['label'], model_year, eval_year, 'validation')

    y_val_proba = model_obj.predict_proba(X_val)[:, 1]
    return best_f1_threshold(y_val, y_val_proba, default_threshold=default_threshold)


def evaluate_one_pair(model_obj, prep_fn, ds, family_cfg, model_year, eval_year, scaler_obj, threshold, threshold_meta, rbf_sampler=None, family_id=None):
    year_to_idx = {int(y): i for i, y in enumerate(ds.year.values)}
    eval_year_idx = year_to_idx[int(eval_year)]

    if scaler_obj is None:
        scale_mode = 'none'
    else:
        scale_mode = 'transform'

    X_test, y_test, _ = prep_fn(
        ds,
        test_pixel_indices,
        eval_year_idx,
        scaler=scaler_obj,
        scaler_mode=scale_mode,
        family_id=family_id,
    )
    if len(X_test) == 0:
        return None

    validate_scaler_features(X_test, scaler_obj, family_cfg['label'], model_year, eval_year, 'test')

    if rbf_sampler is not None:
        X_test = rbf_sampler.transform(X_test)

    validate_model_features(X_test, model_obj, family_cfg['label'], model_year, eval_year, 'test')

    y_proba = model_obj.predict_proba(X_test)[:, 1]
    y_pred = (y_proba >= threshold).astype(int)
    metrics = compute_metrics(y_test, y_pred, y_proba)

    return {
        'model_year': int(model_year),
        'eval_year': int(eval_year),
        'n_test_samples': int(len(y_test)),
        'threshold_used': float(threshold),
        'threshold_source': threshold_meta.get('source', 'unknown'),
        'threshold_reason': threshold_meta.get('reason', ''),
        'n_val_threshold_samples': int(threshold_meta.get('n_val_samples', 0)),
        **metrics,
    }


def evaluate_family(family_id, family_cfg, default_threshold=0.5):
    prep_fn = PREP_FN_BY_KIND[family_cfg['prep_kind']]
    ds = load_family_dataset(family_cfg)
    models_dir = family_cfg['models_dir']

    if not models_dir.exists():
        raise FileNotFoundError(f'Model directory missing: {models_dir.resolve()}')

    years = infer_years_from_models(models_dir, family_cfg['model_template'])
    if not years:
        raise RuntimeError(f'No model years found for {family_id}')

    rbf_sampler = None
    if 'rbf_sampler_path' in family_cfg:
        rbf_path = family_cfg['rbf_sampler_path']
        if rbf_path.exists():
            with open(rbf_path, 'rb') as f:
                rbf_sampler = pickle.load(f)

    family_out_dir = EVAL_DIR / family_id
    family_out_dir.mkdir(parents=True, exist_ok=True)

    status_rows = []

    cache_hits_before = FEATURE_CACHE_STATS['hits']
    cache_misses_before = FEATURE_CACHE_STATS['misses']

    def _run_table_own_year():
        rows = []
        for year in years:
            model_obj = load_model(models_dir, family_cfg['model_template'], year)
            if model_obj is None:
                continue
            scaler_year, scaler_policy = resolve_scaler_year(family_cfg, year, year)
            scaler_obj = load_scaler(models_dir, family_cfg['scaler_template'], scaler_year)

            threshold, threshold_meta = compute_threshold_for_pair(
                model_obj,
                prep_fn,
                ds,
                family_cfg,
                year,
                year,
                scaler_obj,
                rbf_sampler=rbf_sampler,
                default_threshold=default_threshold,
                family_id=family_id,
            )
            result = evaluate_one_pair(
                model_obj,
                prep_fn,
                ds,
                family_cfg,
                year,
                year,
                scaler_obj,
                threshold,
                threshold_meta,
                rbf_sampler=rbf_sampler,
                family_id=family_id,
            )
            if result is None:
                continue
            result.update({
                'family_id': family_id,
                'family_label': family_cfg['label'],
                'table_type': 'own_year',
                'scaler_year_used': int(scaler_year),
                'scaler_policy_used': scaler_policy,
            })
            rows.append(result)
        return pd.DataFrame(rows)

    def _run_table_prior_years():
        rows = []
        for model_year in years:
            model_obj = load_model(models_dir, family_cfg['model_template'], model_year)
            if model_obj is None:
                continue
            for eval_year in [y for y in years if y <= model_year]:
                scaler_year, scaler_policy = resolve_scaler_year(family_cfg, model_year, eval_year)
                scaler_obj = load_scaler(models_dir, family_cfg['scaler_template'], scaler_year)

                threshold, threshold_meta = compute_threshold_for_pair(
                    model_obj,
                    prep_fn,
                    ds,
                    family_cfg,
                    model_year,
                    eval_year,
                    scaler_obj,
                    rbf_sampler=rbf_sampler,
                    default_threshold=default_threshold,
                    family_id=family_id,
                )
                result = evaluate_one_pair(
                    model_obj,
                    prep_fn,
                    ds,
                    family_cfg,
                    model_year,
                    eval_year,
                    scaler_obj,
                    threshold,
                    threshold_meta,
                    rbf_sampler=rbf_sampler,
                    family_id=family_id,
                )
                if result is None:
                    continue
                result.update({
                    'family_id': family_id,
                    'family_label': family_cfg['label'],
                    'table_type': 'prior_years',
                    'scaler_year_used': int(scaler_year),
                    'scaler_policy_used': scaler_policy,
                })
                rows.append(result)
        return pd.DataFrame(rows)

    def _run_table_next_year():
        rows = []
        for model_year in years:
            candidate = model_year + 1
            if candidate not in years:
                continue
            model_obj = load_model(models_dir, family_cfg['model_template'], model_year)
            if model_obj is None:
                continue

            scaler_year, scaler_policy = resolve_scaler_year(family_cfg, model_year, candidate)
            scaler_obj = load_scaler(models_dir, family_cfg['scaler_template'], scaler_year)

            threshold, threshold_meta = compute_threshold_for_pair(
                model_obj,
                prep_fn,
                ds,
                family_cfg,
                model_year,
                candidate,
                scaler_obj,
                rbf_sampler=rbf_sampler,
                default_threshold=default_threshold,
                family_id=family_id,
            )
            result = evaluate_one_pair(
                model_obj,
                prep_fn,
                ds,
                family_cfg,
                model_year,
                candidate,
                scaler_obj,
                threshold,
                threshold_meta,
                rbf_sampler=rbf_sampler,
                family_id=family_id,
            )
            if result is None:
                continue
            result.update({
                'family_id': family_id,
                'family_label': family_cfg['label'],
                'table_type': 'next_year',
                'scaler_year_used': int(scaler_year),
                'scaler_policy_used': scaler_policy,
            })
            rows.append(result)
        return pd.DataFrame(rows)

    def _run_table_cumulative():
        rows = []
        year_to_idx = {int(y): i for i, y in enumerate(ds.year.values)}
        for model_year in years:
            model_obj = load_model(models_dir, family_cfg['model_template'], model_year)
            if model_obj is None:
                continue

            X_blocks = []
            y_blocks = []
            scaler_policies = []
            scaler_years = []
            threshold_rows = []

            for eval_year in [y for y in years if y <= model_year]:
                scaler_year, scaler_policy = resolve_scaler_year(family_cfg, model_year, eval_year)
                scaler_obj = load_scaler(models_dir, family_cfg['scaler_template'], scaler_year)
                if scaler_obj is None and family_cfg['scaler_template'] is not None:
                    continue

                eval_year_idx = year_to_idx[int(eval_year)]
                scale_mode = 'none' if scaler_obj is None else 'transform'
                X_block, y_block, _ = prep_fn(
                    ds,
                    test_pixel_indices,
                    eval_year_idx,
                    scaler=scaler_obj,
                    scaler_mode=scale_mode,
                    family_id=family_id,
                )
                if len(X_block) == 0:
                    continue

                validate_scaler_features(X_block, scaler_obj, family_cfg['label'], model_year, eval_year, 'cumulative_test_block')

                if rbf_sampler is not None:
                    X_block = rbf_sampler.transform(X_block)

                validate_model_features(X_block, model_obj, family_cfg['label'], model_year, eval_year, 'cumulative_test_block')

                X_blocks.append(X_block)
                y_blocks.append(y_block)
                scaler_policies.append(scaler_policy)
                scaler_years.append(int(scaler_year))

                threshold, threshold_meta = compute_threshold_for_pair(
                    model_obj,
                    prep_fn,
                    ds,
                    family_cfg,
                    model_year,
                    eval_year,
                    scaler_obj,
                    rbf_sampler=rbf_sampler,
                    default_threshold=default_threshold,
                    family_id=family_id,
                )
                threshold_rows.append((threshold, threshold_meta))

            if not X_blocks:
                continue

            threshold, threshold_meta = threshold_rows[-1]
            X_test = np.vstack(X_blocks)
            y_test = np.concatenate(y_blocks)

            validate_model_features(X_test, model_obj, family_cfg['label'], model_year, model_year, 'cumulative_test_stack')

            y_proba = model_obj.predict_proba(X_test)[:, 1]
            y_pred = (y_proba >= threshold).astype(int)
            metrics = compute_metrics(y_test, y_pred, y_proba)

            rows.append({
                'family_id': family_id,
                'family_label': family_cfg['label'],
                'table_type': 'cumulative',
                'model_year': int(model_year),
                'eval_year': int(model_year),
                'n_test_samples': int(len(y_test)),
                'years_included': ','.join(str(y) for y in years if y <= model_year),
                'threshold_used': float(threshold),
                'threshold_source': threshold_meta.get('source', 'unknown'),
                'threshold_reason': threshold_meta.get('reason', ''),
                'n_val_threshold_samples': int(threshold_meta.get('n_val_samples', 0)),
                'scaler_year_used': int(scaler_years[-1]),
                'scaler_policy_used': scaler_policies[-1],
                **metrics,
            })
        return pd.DataFrame(rows)

    def _run_table_final_model_each_year():
        final_model = None
        final_model_path = family_cfg.get('final_model_path')
        if final_model_path and final_model_path.exists():
            with open(final_model_path, 'rb') as f:
                final_model = pickle.load(f)
        else:
            return pd.DataFrame([])

        final_scaler = load_final_scaler(family_cfg)
        rows = []
        for eval_year in years:
            if final_scaler is not None:
                scaler_obj = final_scaler
                scaler_year = max(years)
                scaler_policy = 'family_final_scaler'
            else:
                scaler_year, scaler_policy = resolve_scaler_year(family_cfg, max(years), eval_year)
                scaler_obj = load_scaler(models_dir, family_cfg['scaler_template'], scaler_year)
            threshold, threshold_meta = compute_threshold_for_pair(
                final_model,
                prep_fn,
                ds,
                family_cfg,
                max(years),
                eval_year,
                scaler_obj,
                rbf_sampler=rbf_sampler,
                default_threshold=default_threshold,
                family_id=family_id,
            )
            result = evaluate_one_pair(
                final_model,
                prep_fn,
                ds,
                family_cfg,
                max(years),
                eval_year,
                scaler_obj,
                threshold,
                threshold_meta,
                rbf_sampler=rbf_sampler,
                family_id=family_id,
            )
            if result is None:
                continue
            result.update({
                'family_id': family_id,
                'family_label': family_cfg['label'],
                'table_type': 'final_model_each_year',
                'scaler_year_used': int(scaler_year),
                'scaler_policy_used': scaler_policy,
            })
            rows.append(result)
        return pd.DataFrame(rows)

    table_runners = {
        'own_year': _run_table_own_year,
        'prior_years': _run_table_prior_years,
        'next_year': _run_table_next_year,
        'cumulative': _run_table_cumulative,
        'final_model_each_year': _run_table_final_model_each_year,
    }

    table_frames = {}
    for table_name, table_fn in table_runners.items():
        table_path = family_out_dir / f'{family_id}_{table_name}.csv'
        df_table, skipped = load_or_run_table(table_path, table_fn)
        table_frames[table_name] = df_table
        status_rows.append({
            'family_id': family_id,
            'table_name': table_name,
            'skipped_existing': bool(skipped),
            'row_count': int(len(df_table)),
            'csv_path': str(table_path),
        })

    combined = pd.concat([df for df in table_frames.values() if len(df) > 0], ignore_index=True) if table_frames else pd.DataFrame([])
    combined_path = family_out_dir / f'{family_id}_combined.csv'
    save_table(combined, combined_path)

    status_df = pd.DataFrame(status_rows)
    save_table(status_df, family_out_dir / f'{family_id}_status.csv')

    cache_hits_after = FEATURE_CACHE_STATS['hits']
    cache_misses_after = FEATURE_CACHE_STATS['misses']
    family_cache_hits = int(cache_hits_after - cache_hits_before)
    family_cache_misses = int(cache_misses_after - cache_misses_before)
    if _FEATURE_CACHE.enabled(family_id):
        total_requests = family_cache_hits + family_cache_misses
        hit_rate = (100.0 * family_cache_hits / total_requests) if total_requests > 0 else 0.0
        print(
            f"Feature cache stats [{family_id}] -> hits={family_cache_hits:,}, misses={family_cache_misses:,}, "
            f"hit_rate={hit_rate:.1f}%, entries={len(FEATURE_CACHE):,}"
        )

    return table_frames, combined, status_df


def run_all_families(default_threshold=0.5):
    all_family_combined = []
    all_status = []

    for family_id, family_cfg in FAMILIES.items():
        print('\n' + '=' * 100)
        print(f"FAMILY: {family_id} | {family_cfg['label']}")
        print('=' * 100)
        try:
            _, family_combined_df, family_status_df = evaluate_family(
                family_id=family_id,
                family_cfg=family_cfg,
                default_threshold=default_threshold,
            )
            if len(family_combined_df) > 0:
                all_family_combined.append(family_combined_df)
            all_status.append(family_status_df)
        except Exception as exc:
            all_status.append(pd.DataFrame([{
                'family_id': family_id,
                'table_name': '__family_failure__',
                'skipped_existing': False,
                'row_count': 0,
                'csv_path': '',
                'error': str(exc),
            }]))
            print(f'ERROR in family {family_id}: {exc}')

    global_combined_df = pd.concat(all_family_combined, ignore_index=True) if all_family_combined else pd.DataFrame([])
    global_status_df = pd.concat(all_status, ignore_index=True) if all_status else pd.DataFrame([])

    save_table(global_combined_df, EVAL_DIR / 'all_families_combined.csv')
    save_table(global_status_df, EVAL_DIR / 'all_families_status.csv')

    print('\n' + '=' * 100)
    print('GLOBAL SUMMARY')
    print('=' * 100)
    print(f'Combined rows: {len(global_combined_df):,}')
    print(f'Status rows:   {len(global_status_df):,}')
    print(
        f"Feature cache totals -> hits={FEATURE_CACHE_STATS['hits']:,}, "
        f"misses={FEATURE_CACHE_STATS['misses']:,}, entries={len(FEATURE_CACHE):,}"
    )

    return global_combined_df, global_status_df


# Run this cell when you are ready for full evaluation.
global_combined_results_df, global_status_df = run_all_families(default_threshold=0.5)

#print('Pipeline implementation complete. Uncomment the last line to execute full evaluation.')

====================================================================================================
FAMILY: baseline | SGD Baseline
====================================================================================================
SKIP existing table: baseline_own_year.csv
SKIP existing table: baseline_prior_years.csv
SKIP existing table: baseline_next_year.csv
SKIP existing table: baseline_cumulative.csv
SKIP existing table: baseline_final_model_each_year.csv
ERROR in family baseline: No columns to parse from file

====================================================================================================
FAMILY: huber | SGD Huber
====================================================================================================

C:\Users\bartu\AppData\Local\Temp\ipykernel_30208\2260530053.py:77: RuntimeWarning: Mean of empty slice
  s2_mean_per_pixel = np.nanmean(s2_all_years, axis=1)

ERROR in family huber: X has 22 features, but StandardScaler is expecting 14 features as input.

====================================================================================================
FAMILY: lagged_features | SGD Lagged Features
====================================================================================================
SKIP existing table: lagged_features_own_year.csv
SKIP existing table: lagged_features_prior_years.csv
SKIP existing table: lagged_features_next_year.csv
SKIP existing table: lagged_features_cumulative.csv
SKIP existing table: lagged_features_final_model_each_year.csv
ERROR in family lagged_features: No columns to parse from file

====================================================================================================
FAMILY: lagged_features_incremental_scaler | SGD Lagged Features (Incremental Scaler)
====================================================================================================
SKIP existing table: lagged_features_incremental_scaler_own_year.csv
SKIP existing table: lagged_features_incremental_scaler_prior_years.csv
SKIP existing table: lagged_features_incremental_scaler_next_year.csv
SKIP existing table: lagged_features_incremental_scaler_cumulative.csv
SKIP existing table: lagged_features_incremental_scaler_final_model_each_year.csv
ERROR in family lagged_features_incremental_scaler: No columns to parse from file

====================================================================================================
FAMILY: neighbours | SGD Neighbours
====================================================================================================
SKIP existing table: neighbours_own_year.csv
SKIP existing table: neighbours_prior_years.csv
SKIP existing table: neighbours_next_year.csv
SKIP existing table: neighbours_cumulative.csv
SKIP existing table: neighbours_final_model_each_year.csv
ERROR in family neighbours: No columns to parse from file

====================================================================================================
FAMILY: prevyears_monthly_features | SGD Prevyears + Monthly
====================================================================================================
SKIP existing table: prevyears_monthly_features_own_year.csv
SKIP existing table: prevyears_monthly_features_prior_years.csv
SKIP existing table: prevyears_monthly_features_next_year.csv
SKIP existing table: prevyears_monthly_features_cumulative.csv
SKIP existing table: prevyears_monthly_features_final_model_each_year.csv
ERROR in family prevyears_monthly_features: No columns to parse from file

====================================================================================================
FAMILY: prevyears_monthly_features_experience_replay | SGD Prevyears + Monthly + Replay
====================================================================================================
ERROR in family prevyears_monthly_features_experience_replay: Model directory missing: C:\Users\bartu\Desktop\Fonda-scikit - Git\models_prevyears_monthly_features_experience_replay

====================================================================================================
FAMILY: prevyears_monthly_features_incremental_scaler | SGD Prevyears + Monthly (Incremental Scaler)
====================================================================================================
SKIP existing table: prevyears_monthly_features_incremental_scaler_own_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_prior_years.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_next_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_cumulative.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_final_model_each_year.csv
Feature cache stats [prevyears_monthly_features_incremental_scaler] -> hits=0, misses=0, hit_rate=0.0%, entries=0

====================================================================================================
FAMILY: prevyears_monthly_features_incremental_scaler_experience_replay | SGD Prevyears + Monthly (Incremental Scaler + Replay)
====================================================================================================
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_own_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_prior_years.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_next_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_cumulative.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_final_model_each_year.csv
Feature cache stats [prevyears_monthly_features_incremental_scaler_experience_replay] -> hits=0, misses=0, hit_rate=0.0%, entries=0

====================================================================================================
FAMILY: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2 | SGD Prevyears + Monthly (Incremental Scaler + Replay RR=0.2)
====================================================================================================
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_own_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_prior_years.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_next_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_cumulative.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_final_model_each_year.csv
ERROR in family prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2: No columns to parse from file

====================================================================================================
FAMILY: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3 | SGD Prevyears + Monthly (Incremental Scaler + Replay RR=0.3)
====================================================================================================
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_own_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_prior_years.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_next_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_cumulative.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_final_model_each_year.csv
ERROR in family prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3: No columns to parse from file

====================================================================================================
FAMILY: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4 | SGD Prevyears + Monthly (Incremental Scaler + Replay RR=0.4)
====================================================================================================
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_own_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_prior_years.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_next_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_cumulative.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_final_model_each_year.csv
ERROR in family prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4: No columns to parse from file

====================================================================================================
FAMILY: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5 | SGD Prevyears + Monthly (Incremental Scaler + Replay RR=0.5)
====================================================================================================
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_own_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_prior_years.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_next_year.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_cumulative.csv
SKIP existing table: prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_final_model_each_year.csv
Feature cache stats [prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5] -> hits=0, misses=0, hit_rate=0.0%, entries=0

====================================================================================================
FAMILY: prevyears_monthly_features_rbf | SGD Prevyears + Monthly (RBF)
====================================================================================================
SKIP existing table: prevyears_monthly_features_rbf_own_year.csv
SKIP existing table: prevyears_monthly_features_rbf_prior_years.csv
SKIP existing table: prevyears_monthly_features_rbf_next_year.csv
SKIP existing table: prevyears_monthly_features_rbf_cumulative.csv
SKIP existing table: prevyears_monthly_features_rbf_final_model_each_year.csv

====================================================================================================
FAMILY: mlp_prevyears_monthly_features_incremental_scaler | MLP Prevyears + Monthly (Incremental Scaler)
====================================================================================================
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_own_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_prior_years.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_next_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_cumulative.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_final_model_each_year.csv
Feature cache stats [mlp_prevyears_monthly_features_incremental_scaler] -> hits=0, misses=0, hit_rate=0.0%, entries=0

====================================================================================================
FAMILY: mlp_prevyears_monthly_features_incremental_scaler_experience_replay | MLP Prevyears + Monthly (Incremental Scaler + Replay)
====================================================================================================
ERROR in family mlp_prevyears_monthly_features_incremental_scaler_experience_replay: Model directory missing: C:\Users\bartu\Desktop\Fonda-scikit - Git\models_mlp_prevyears_monthly_features_incremental_scaler_experience_replay

====================================================================================================
FAMILY: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2 | MLP Prevyears + Monthly (Incremental Scaler + Replay RR=0.2)
====================================================================================================
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_own_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_prior_years.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_next_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_cumulative.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_final_model_each_year.csv
Feature cache stats [mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2] -> hits=0, misses=0, hit_rate=0.0%, entries=0

====================================================================================================
FAMILY: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3 | MLP Prevyears + Monthly (Incremental Scaler + Replay RR=0.3)
====================================================================================================
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_own_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_prior_years.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_next_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_cumulative.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_final_model_each_year.csv
Feature cache stats [mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3] -> hits=0, misses=0, hit_rate=0.0%, entries=0

====================================================================================================
FAMILY: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4 | MLP Prevyears + Monthly (Incremental Scaler + Replay RR=0.4)
====================================================================================================
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_own_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_prior_years.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_next_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_cumulative.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_final_model_each_year.csv
Feature cache stats [mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4] -> hits=0, misses=0, hit_rate=0.0%, entries=0

====================================================================================================
FAMILY: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5 | MLP Prevyears + Monthly (Incremental Scaler + Replay RR=0.5)
====================================================================================================
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_own_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_prior_years.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_next_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_cumulative.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_final_model_each_year.csv
Feature cache stats [mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5] -> hits=0, misses=0, hit_rate=0.0%, entries=0

====================================================================================================
FAMILY: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_PR_0.10 | MLP Prevyears + Monthly (Incremental Scaler + Replay RR=0.2, PR=0.10)
====================================================================================================
ERROR in family mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_PR_0.10: Model directory missing: C:\Users\bartu\Desktop\Fonda-scikit - Git\models_mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_PR_0.10

====================================================================================================
FAMILY: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_PR_0.10 | MLP Prevyears + Monthly (Incremental Scaler + Replay RR=0.3, PR=0.10)
====================================================================================================
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_PR_0.10_own_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_PR_0.10_prior_years.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_PR_0.10_next_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_PR_0.10_cumulative.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_PR_0.10_final_model_each_year.csv
Feature cache stats [mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.3_PR_0.10] -> hits=0, misses=0, hit_rate=0.0%, entries=0

====================================================================================================
FAMILY: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_PR_0.10 | MLP Prevyears + Monthly (Incremental Scaler + Replay RR=0.4, PR=0.10)
====================================================================================================
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_PR_0.10_own_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_PR_0.10_prior_years.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_PR_0.10_next_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_PR_0.10_cumulative.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_PR_0.10_final_model_each_year.csv
Feature cache stats [mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.4_PR_0.10] -> hits=0, misses=0, hit_rate=0.0%, entries=0

====================================================================================================
FAMILY: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_PR_0.10 | MLP Prevyears + Monthly (Incremental Scaler + Replay RR=0.5, PR=0.10)
====================================================================================================
ERROR in family mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_PR_0.10: No model years found for mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_PR_0.10

====================================================================================================
FAMILY: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_PR_0.15 | MLP Prevyears + Monthly (Incremental Scaler + Replay RR=0.2, PR=0.15)
====================================================================================================
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_PR_0.15_own_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_PR_0.15_prior_years.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_PR_0.15_next_year.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_PR_0.15_cumulative.csv
SKIP existing table: mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_PR_0.15_final_model_each_year.csv
Feature cache stats [mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_PR_0.15] -> hits=0, misses=0, hit_rate=0.0%, entries=0

====================================================================================================

C:\Users\bartu\AppData\Local\Temp\ipykernel_30208\2260530053.py:77: RuntimeWarning: Mean of empty slice
  s2_mean_per_pixel = np.nanmean(s2_all_years, axis=1)

In [ ]:
# Section: Table-structured metric matrices (years as columns)
# F1 and PR AUC are displayed as separate tables.

summary_root = EVAL_DIR / 'summary_matrices'
summary_root.mkdir(parents=True, exist_ok=True)

# Remove legacy single prior-years exports to enforce per-model-year output format.
legacy_prior_paths = [
    summary_root / 'metric_matrix_prior_years_f1.csv',
    summary_root / 'metric_matrix_prior_years_pr_auc.csv',
]
for legacy_path in legacy_prior_paths:
    if legacy_path.exists():
        legacy_path.unlink()
        print(f'Removed legacy export: {legacy_path.name}')

required_cols = ['family_id', 'table_type', 'eval_year', 'f1_score', 'pr_auc']
all_frames = []
skipped_families = []

for family_id, family_cfg in FAMILIES.items():
    family_dir = EVAL_DIR / family_id
    combined_csv = family_dir / f'{family_id}_combined.csv'

    df = None
    reason = None

    if combined_csv.exists():
        try:
            df = pd.read_csv(combined_csv)
        except Exception as exc:
            reason = f'failed reading combined csv ({exc})'
    else:
        fallback_files = sorted(family_dir.glob(f'{family_id}_*.csv')) if family_dir.exists() else []
        fallback_files = [p for p in fallback_files if not p.name.endswith('_status.csv') and not p.name.endswith('_combined.csv')]
        if fallback_files:
            frames = []
            for file_path in fallback_files:
                try:
                    frames.append(pd.read_csv(file_path))
                except Exception:
                    pass
            if frames:
                df = pd.concat(frames, ignore_index=True)
            else:
                reason = 'fallback table csv files could not be read'
        else:
            reason = 'combined csv not found'

    if df is None or df.empty:
        skipped_families.append((family_id, reason or 'empty dataframe'))
        continue

    missing_required = [c for c in required_cols if c not in df.columns]
    if missing_required:
        skipped_families.append((family_id, f'missing columns: {missing_required}'))
        continue

    # model_year is required for per-model-year prior tables; keep NaN for table types where unavailable.
    if 'model_year' not in df.columns:
        df['model_year'] = np.nan

    df = df[required_cols + ['model_year']].copy()
    df['family_id'] = df['family_id'].fillna(family_id).astype(str)
    df['table_type'] = df['table_type'].astype(str)
    df['eval_year'] = pd.to_numeric(df['eval_year'], errors='coerce')
    df['model_year'] = pd.to_numeric(df['model_year'], errors='coerce')
    df['f1_score'] = pd.to_numeric(df['f1_score'], errors='coerce')
    df['pr_auc'] = pd.to_numeric(df['pr_auc'], errors='coerce')
    df = df.dropna(subset=['eval_year'])
    all_frames.append(df)

if not all_frames:
    print('No usable evaluation outputs found for matrix generation.')
else:
    results_df = pd.concat(all_frames, ignore_index=True)

    # Keep standard matrix exports for non-prior table types.
    table_types = [
        'own_year',
        'next_year',
        'cumulative',
        'final_model_each_year',
    ]

    metric_specs = [
        ('f1_score', 'f1'),
        ('pr_auc', 'pr_auc'),
    ]

    # Display/export labels for RR replay families (including PR variants); base replay rows remain unchanged.
    # Every family now carries its own display label (src/eval/families.py);
    # this used to be a second, separately-maintained, only-partially-covering
    # rename dict here. Derived, not hand-written, so a family added without a
    # short_label is a build-time omission instead of a raw id in a report.
    row_label_renames = {fid: cfg['short_label'] for fid, cfg in FAMILIES.items()}

    summary_outputs = {}

    for table_type in table_types:
        table_slice = results_df[results_df['table_type'] == table_type].copy()
        if table_slice.empty:
            print(f'[{table_type}] No rows available.')
            continue

        print('\n' + '=' * 100)
        print(f'TABLE: {table_type}')
        print('Rows are family_id. Columns are evaluation years.')
        print('Duplicate family-year rows are reduced using mean across contributing rows.')
        print('=' * 100)

        for metric_col, metric_label in metric_specs:
            metric_df = table_slice[['family_id', 'eval_year', metric_col]].copy()
            metric_df = metric_df.dropna(subset=[metric_col])

            if metric_df.empty:
                print(f'[{table_type}] {metric_label}: no non-null values available.')
                continue

            matrix_df = (
                metric_df
                .groupby(['family_id', 'eval_year'], as_index=False)[metric_col]
                .mean()
                .pivot(index='family_id', columns='eval_year', values=metric_col)
                .sort_index(axis=0)
                .sort_index(axis=1)
            )

            matrix_df.columns = [str(int(c)) if pd.notna(c) else str(c) for c in matrix_df.columns]
            matrix_df = matrix_df.reset_index().rename(columns={'family_id': 'row'})
            matrix_df['row'] = matrix_df['row'].replace(row_label_renames)

            summary_outputs[(table_type, metric_label)] = matrix_df

            export_path = summary_root / f'metric_matrix_{table_type}_{metric_label}.csv'
            matrix_df.to_csv(export_path, index=False)

            print(f'\n{metric_label.upper()} matrix')
            display(matrix_df)
            print(f'Saved: {export_path}')

    # Dedicated end section: one prior-years table per model year (columns grow with model year).
    prior_slice = results_df[results_df['table_type'] == 'prior_years'].copy()

    print('\n' + '=' * 100)
    print('TABLE SECTION: prior_years (per model year)')
    print('Each table is one model year. Rows are family_id. Columns are eval_year <= model_year.')
    print('=' * 100)

    if prior_slice.empty:
        print('[prior_years] No rows available.')
    elif prior_slice['model_year'].dropna().empty:
        print('[prior_years] Missing model_year values; cannot build per-model-year tables.')
    else:
        model_years = sorted(prior_slice['model_year'].dropna().astype(int).unique())

        for model_year in model_years:
            model_slice = prior_slice[prior_slice['model_year'].astype('Int64') == model_year].copy()
            if model_slice.empty:
                continue

            print('\n' + '-' * 100)
            print(f'PRIOR MODEL YEAR: {model_year}')
            print('-' * 100)

            for metric_col, metric_label in metric_specs:
                metric_df = model_slice[['family_id', 'eval_year', metric_col]].copy()
                metric_df = metric_df.dropna(subset=[metric_col])

                if metric_df.empty:
                    print(f'[prior_years_model_{model_year}] {metric_label}: no non-null values available.')
                    continue

                matrix_df = (
                    metric_df
                    .groupby(['family_id', 'eval_year'], as_index=False)[metric_col]
                    .mean()
                    .pivot(index='family_id', columns='eval_year', values=metric_col)
                    .sort_index(axis=0)
                    .sort_index(axis=1)
                )

                matrix_df.columns = [str(int(c)) if pd.notna(c) else str(c) for c in matrix_df.columns]
                matrix_df = matrix_df.reset_index().rename(columns={'family_id': 'row'})
                matrix_df['row'] = matrix_df['row'].replace(row_label_renames)

                table_key = f'prior_years_model_{model_year}'
                summary_outputs[(table_key, metric_label)] = matrix_df

                export_path = summary_root / f'metric_matrix_{table_key}_{metric_label}.csv'
                matrix_df.to_csv(export_path, index=False)

                print(f'\n{metric_label.upper()} matrix')
                display(matrix_df)
                print(f'Saved: {export_path}')

    if skipped_families:
        print('\nSkipped families (missing/invalid outputs):')
        for family_name, reason in skipped_families:
            print(f' - {family_name}: {reason}')

    overall_summary = pd.DataFrame([
        {
            'table_type': table_type,
            'metric': metric_label,
            'row_count': len(df_out),
        }
        for (table_type, metric_label), df_out in summary_outputs.items()
    ])

    overall_export_path = summary_root / 'metric_matrix_overview.csv'
    overall_summary.to_csv(overall_export_path, index=False)

    print('\nSummary matrix exports complete.')
    print(f'Output folder: {summary_root}')
    display(overall_summary.sort_values(['table_type', 'metric']).reset_index(drop=True))

====================================================================================================
TABLE: own_year
Rows are family_id. Columns are evaluation years.
Duplicate family-year rows are reduced using mean across contributing rows.
====================================================================================================

F1 matrix

,row,2017,2018,2019,2020,2021,2022
0,baseline,0.181211,0.394452,0.218509,0.256754,0.230862,0.258414
1,lagged_features,0.183724,0.394536,0.393827,0.419739,0.408259,0.413103
2,lagged_features_incremental_scaler,0.199615,0.395409,0.394097,0.412271,0.401910,0.411766
3,mlp_prevyears_monthly_features_incremental_scaler,0.263363,0.450257,0.468561,0.486295,0.470570,0.473149
4,mlp_experience_replay_RR_0.2,0.253968,0.449656,0.468287,0.493626,0.475431,0.493281
5,mlp_experience_replay_RR_0.2_PR_0.15,0.254553,0.443568,0.476202,0.484972,0.476525,0.475977
6,mlp_experience_replay_RR_0.3,0.257549,0.452124,0.470972,0.492685,0.475714,0.472905
7,mlp_experience_replay_RR_0.3_PR_0.10,0.258759,0.443730,0.461814,0.491207,0.476782,0.478229
8,mlp_experience_replay_RR_0.3_PR_0.15,0.267114,0.445327,0.465927,0.484842,0.477080,0.480458
9,mlp_experience_replay_RR_0.4,0.261505,0.450813,0.462095,0.484699,0.470926,0.469834
10,mlp_experience_replay_RR_0.4_PR_0.10,0.270914,0.450734,0.467719,0.496405,0.478935,0.484380
11,mlp_experience_replay_RR_0.4_PR_0.15,0.270914,0.456370,0.476596,0.491154,0.468613,0.483486
12,mlp_experience_replay_RR_0.5,0.266522,0.445370,0.475107,0.497112,0.473050,0.461663
13,mlp_experience_replay_RR_0.5_PR_0.15,0.264416,0.452978,0.462227,0.494093,0.473355,0.485432
14,mlp_experience_replay_confidently_correct_memo...,0.254553,0.446245,0.475236,0.487451,0.470918,0.481567
15,mlp_experience_replay_confidently_correct_memo...,0.254553,0.442857,0.466787,0.483842,0.477130,0.472664
16,mlp_experience_replay_confidently_correct_memo...,0.270914,0.446613,0.465934,0.483531,0.463485,0.471373
17,mlp_experience_replay_confidently_correct_memo...,0.264416,0.448491,0.468250,0.491770,0.475783,0.475926
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.254553,0.442323,0.466492,0.480815,0.466952,0.476366
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.267114,0.449884,0.465055,0.501752,0.471366,0.480506
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.270914,0.454317,0.466153,0.492846,0.481376,0.483565
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.264416,0.456053,0.470489,0.492516,0.484973,0.477990
22,mlp_experience_replay_uncertainity_prioritizat...,0.262993,0.446449,0.468904,0.489940,0.484355,0.466181
23,mlp_experience_replay_uncertainity_prioritizat...,0.257549,0.450579,0.473401,0.492213,0.475155,0.480314
24,mlp_misclassification_buffer_RR_0.3,0.262993,0.446174,0.470635,0.484667,0.462473,0.492810
25,neighbours,0.187932,0.395161,0.185108,0.214480,0.198482,0.231862
26,prevyears_monthly_features,0.180581,0.405588,0.417279,0.446585,0.407614,0.415744
27,prevyears_monthly_features_experience_replay,0.187821,0.409010,0.409905,0.439004,0.404064,0.416170
28,prevyears_monthly_features_incremental_scaler,0.192974,0.412624,0.411193,0.437638,0.413210,0.420131
29,prevyears_monthly_features_incremental_scaler_...,0.186693,0.396712,0.401195,0.431044,0.390829,0.399650
30,sgd_experience_replay_RR_0.2,0.180836,0.404282,0.402829,0.429426,0.390667,0.407070
31,sgd_experience_replay_RR_0.3,0.196554,0.400056,0.403886,0.430640,0.404053,0.391797
32,sgd_experience_replay_RR_0.4,0.190390,0.399406,0.399413,0.432000,0.396018,0.396356
33,sgd_experience_replay_RR_0.5,0.197039,0.396026,0.400979,0.441788,0.399003,0.404232
34,prevyears_monthly_features_rbf,0.035619,0.043850,0.040473,0.053503,0.033240,0.061141

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_own_year_f1.csv

PR_AUC matrix

,row,2017,2018,2019,2020,2021,2022
0,baseline,0.102965,0.379073,0.160839,0.193445,0.163037,0.195861
1,lagged_features,0.109286,0.378105,0.343162,0.385600,0.395786,0.386227
2,lagged_features_incremental_scaler,0.121508,0.375879,0.341089,0.376934,0.386522,0.386627
3,mlp_prevyears_monthly_features_incremental_scaler,0.203730,0.444538,0.425024,0.454080,0.440404,0.454931
4,mlp_experience_replay_RR_0.2,0.194117,0.442351,0.431550,0.467488,0.438441,0.472962
5,mlp_experience_replay_RR_0.2_PR_0.15,0.193359,0.429477,0.438943,0.454944,0.440482,0.455022
6,mlp_experience_replay_RR_0.3,0.184205,0.441084,0.431101,0.451725,0.439322,0.452903
7,mlp_experience_replay_RR_0.3_PR_0.10,0.185111,0.433883,0.422023,0.455221,0.450059,0.457294
8,mlp_experience_replay_RR_0.3_PR_0.15,0.201416,0.437488,0.421863,0.452702,0.449200,0.453089
9,mlp_experience_replay_RR_0.4,0.195044,0.443769,0.427322,0.453357,0.437619,0.458092
10,mlp_experience_replay_RR_0.4_PR_0.10,0.199051,0.444792,0.429570,0.461238,0.447627,0.462808
11,mlp_experience_replay_RR_0.4_PR_0.15,0.199051,0.447425,0.438333,0.448996,0.437317,0.463495
12,mlp_experience_replay_RR_0.5,0.197084,0.433662,0.439158,0.464704,0.447323,0.451441
13,mlp_experience_replay_RR_0.5_PR_0.15,0.193524,0.443333,0.425234,0.454551,0.442718,0.466948
14,mlp_experience_replay_confidently_correct_memo...,0.193359,0.439391,0.436605,0.457256,0.442651,0.464229
15,mlp_experience_replay_confidently_correct_memo...,0.193359,0.438024,0.424983,0.454236,0.443492,0.462309
16,mlp_experience_replay_confidently_correct_memo...,0.199051,0.440433,0.428609,0.447677,0.440395,0.453179
17,mlp_experience_replay_confidently_correct_memo...,0.193524,0.437585,0.432147,0.455378,0.438188,0.466160
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.193359,0.435702,0.420814,0.445869,0.431523,0.474515
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.201416,0.440620,0.420219,0.470023,0.447988,0.478690
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.199051,0.443491,0.426746,0.459915,0.450295,0.471639
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.193524,0.443531,0.427612,0.461833,0.441211,0.459895
22,mlp_experience_replay_uncertainity_prioritizat...,0.203925,0.438872,0.433359,0.460230,0.451228,0.446195
23,mlp_experience_replay_uncertainity_prioritizat...,0.184205,0.437642,0.432481,0.467084,0.448151,0.463931
24,mlp_misclassification_buffer_RR_0.3,0.203925,0.436951,0.423470,0.463117,0.432253,0.472778
25,neighbours,0.111358,0.383249,0.120917,0.152466,0.128176,0.153380
26,prevyears_monthly_features,0.105772,0.389604,0.363116,0.412449,0.382962,0.392930
27,prevyears_monthly_features_experience_replay,0.104466,0.395264,0.355973,0.403962,0.385958,0.397788
28,prevyears_monthly_features_incremental_scaler,0.112571,0.395498,0.359045,0.403619,0.391261,0.401422
29,prevyears_monthly_features_incremental_scaler_...,0.105441,0.381160,0.343636,0.388120,0.358327,0.376471
30,sgd_experience_replay_RR_0.2,0.096443,0.391483,0.347802,0.391189,0.365328,0.381657
31,sgd_experience_replay_RR_0.3,0.107887,0.383693,0.348980,0.393052,0.376125,0.370231
32,sgd_experience_replay_RR_0.4,0.105767,0.379016,0.347437,0.394471,0.373436,0.369755
33,sgd_experience_replay_RR_0.5,0.109380,0.377575,0.346834,0.404802,0.367220,0.378073
34,prevyears_monthly_features_rbf,0.017331,0.019169,0.019136,0.029920,0.016893,0.029462

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_own_year_pr_auc.csv

====================================================================================================
TABLE: next_year
Rows are family_id. Columns are evaluation years.
Duplicate family-year rows are reduced using mean across contributing rows.
====================================================================================================

F1 matrix

,row,2018,2019,2020,2021,2022
0,baseline,0.243896,0.163483,0.246205,0.206587,0.230355
1,lagged_features,0.247276,0.240764,0.405824,0.387560,0.399741
2,lagged_features_incremental_scaler,0.247878,0.249083,0.409433,0.367458,0.405740
3,mlp_prevyears_monthly_features_incremental_scaler,0.288320,0.309558,0.476199,0.433469,0.379961
4,mlp_experience_replay_RR_0.2,0.281463,0.283552,0.476170,0.445297,0.414717
5,mlp_experience_replay_RR_0.2_PR_0.15,0.283357,0.296792,0.468033,0.412990,0.406051
6,mlp_experience_replay_RR_0.3,0.268358,0.299923,0.479623,0.451202,0.405487
7,mlp_experience_replay_RR_0.3_PR_0.10,0.268288,0.288388,0.476080,0.451022,0.392498
8,mlp_experience_replay_RR_0.3_PR_0.15,0.286327,0.239807,0.477152,0.454135,0.382737
9,mlp_experience_replay_RR_0.4,0.291381,0.259287,0.465591,0.416548,0.383193
10,mlp_experience_replay_RR_0.4_PR_0.10,0.294984,0.288070,0.476082,0.441936,0.382467
11,mlp_experience_replay_RR_0.4_PR_0.15,0.294984,0.304651,0.476435,0.447042,0.392076
12,mlp_experience_replay_RR_0.5,0.292283,0.287004,0.472161,0.444561,0.416025
13,mlp_experience_replay_RR_0.5_PR_0.15,0.289693,0.319680,0.468632,0.438140,0.405744
14,mlp_experience_replay_confidently_correct_memo...,0.283357,0.292502,0.475515,0.461239,0.423934
15,mlp_experience_replay_confidently_correct_memo...,0.283357,0.273850,0.468961,0.449394,0.405121
16,mlp_experience_replay_confidently_correct_memo...,0.294984,0.275203,0.466231,0.450568,0.418959
17,mlp_experience_replay_confidently_correct_memo...,0.289693,0.297712,0.466769,0.451081,0.411697
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.283357,0.257780,0.474270,0.408928,0.365555
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.286327,0.248797,0.476148,0.415145,0.400558
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.294984,0.226229,0.480753,0.434959,0.389384
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.289693,0.271731,0.483007,0.418194,0.402027
22,mlp_experience_replay_uncertainity_prioritizat...,0.284592,0.265343,0.473207,0.459101,0.396709
23,mlp_experience_replay_uncertainity_prioritizat...,0.268358,0.292536,0.478365,0.459577,0.378879
24,mlp_misclassification_buffer_RR_0.3,0.284592,0.232064,0.478962,0.427536,0.367210
25,neighbours,0.241945,0.143041,0.194067,0.186578,0.215954
26,prevyears_monthly_features,0.214082,0.227304,0.425967,0.405327,0.404061
27,prevyears_monthly_features_experience_replay,0.239897,0.268489,0.431844,0.376319,0.414457
28,prevyears_monthly_features_incremental_scaler,0.240732,0.270434,0.435447,0.378065,0.422386
29,prevyears_monthly_features_incremental_scaler_...,0.238030,0.298743,0.432249,0.379962,0.364545
30,sgd_experience_replay_RR_0.2,0.232663,0.293679,0.434239,0.367872,0.376476
31,sgd_experience_replay_RR_0.3,0.364884,0.356624,0.427502,0.375167,0.384428
32,sgd_experience_replay_RR_0.4,0.371830,0.371393,0.427778,0.374404,0.384615
33,sgd_experience_replay_RR_0.5,0.364994,0.361506,0.426118,0.391485,0.374750
34,prevyears_monthly_features_rbf,0.043935,0.040609,0.056100,0.033431,0.061033

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_next_year_f1.csv

PR_AUC matrix

,row,2018,2019,2020,2021,2022
0,baseline,0.191554,0.102961,0.190194,0.151233,0.163229
1,lagged_features,0.207824,0.172229,0.367978,0.363948,0.375924
2,lagged_features_incremental_scaler,0.200425,0.190795,0.371685,0.345166,0.380979
3,mlp_prevyears_monthly_features_incremental_scaler,0.247497,0.251474,0.431737,0.391032,0.352896
4,mlp_experience_replay_RR_0.2,0.239375,0.237289,0.436000,0.409829,0.392859
5,mlp_experience_replay_RR_0.2_PR_0.15,0.241964,0.242947,0.424737,0.361792,0.380430
6,mlp_experience_replay_RR_0.3,0.224136,0.243402,0.442468,0.413217,0.389238
7,mlp_experience_replay_RR_0.3_PR_0.10,0.220126,0.224453,0.430437,0.416370,0.369755
8,mlp_experience_replay_RR_0.3_PR_0.15,0.243062,0.185980,0.431644,0.420875,0.363884
9,mlp_experience_replay_RR_0.4,0.251917,0.206172,0.427734,0.381370,0.360068
10,mlp_experience_replay_RR_0.4_PR_0.10,0.250913,0.236302,0.433348,0.412906,0.359607
11,mlp_experience_replay_RR_0.4_PR_0.15,0.250913,0.271645,0.432306,0.399322,0.371234
12,mlp_experience_replay_RR_0.5,0.251585,0.225828,0.430825,0.408056,0.392420
13,mlp_experience_replay_RR_0.5_PR_0.15,0.250951,0.270202,0.419546,0.407862,0.386769
14,mlp_experience_replay_confidently_correct_memo...,0.241964,0.225387,0.434868,0.421741,0.394275
15,mlp_experience_replay_confidently_correct_memo...,0.241964,0.225127,0.430435,0.396530,0.379850
16,mlp_experience_replay_confidently_correct_memo...,0.250913,0.236373,0.423762,0.413225,0.392296
17,mlp_experience_replay_confidently_correct_memo...,0.250951,0.246087,0.423422,0.410909,0.388392
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.241964,0.187675,0.425938,0.345804,0.337330
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.243062,0.195489,0.429953,0.379250,0.371676
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.250913,0.190711,0.437832,0.385738,0.366267
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.250951,0.209329,0.435809,0.365718,0.369498
22,mlp_experience_replay_uncertainity_prioritizat...,0.239891,0.216321,0.436021,0.430738,0.376082
23,mlp_experience_replay_uncertainity_prioritizat...,0.224136,0.258911,0.437348,0.424960,0.365203
24,mlp_misclassification_buffer_RR_0.3,0.239891,0.199350,0.439966,0.391332,0.335354
25,neighbours,0.185573,0.098154,0.135317,0.120078,0.142776
26,prevyears_monthly_features,0.166298,0.156332,0.385069,0.382025,0.367659
27,prevyears_monthly_features_experience_replay,0.189826,0.206363,0.389476,0.350253,0.375443
28,prevyears_monthly_features_incremental_scaler,0.199473,0.209428,0.394328,0.349295,0.383401
29,prevyears_monthly_features_incremental_scaler_...,0.191721,0.243183,0.387096,0.349419,0.330153
30,sgd_experience_replay_RR_0.2,0.163672,0.244294,0.392602,0.344855,0.346435
31,sgd_experience_replay_RR_0.3,0.335033,0.309122,0.386839,0.353436,0.354241
32,sgd_experience_replay_RR_0.4,0.341833,0.328252,0.386709,0.358281,0.356305
33,sgd_experience_replay_RR_0.5,0.337284,0.317057,0.385857,0.365209,0.346482
34,prevyears_monthly_features_rbf,0.021106,0.018987,0.027887,0.017117,0.029913

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_next_year_pr_auc.csv

====================================================================================================
TABLE: cumulative
Rows are family_id. Columns are evaluation years.
Duplicate family-year rows are reduced using mean across contributing rows.
====================================================================================================

F1 matrix

,row,2017,2018,2019,2020,2021,2022
0,baseline,0.181211,0.221779,0.215445,0.241330,0.228813,0.210475
1,lagged_features,0.183724,0.222375,0.256193,0.292592,0.299688,0.303179
2,lagged_features_incremental_scaler,0.199615,0.272308,0.269523,0.294077,0.289207,0.337086
3,mlp_prevyears_monthly_features_incremental_scaler,0.263363,0.314757,0.166757,0.175981,0.198306,0.181936
4,mlp_experience_replay_RR_0.2,0.253968,0.343755,0.387562,0.414310,0.422439,0.431055
5,mlp_experience_replay_RR_0.2_PR_0.15,0.254553,0.349569,0.388798,0.414413,0.426083,0.416546
6,mlp_experience_replay_RR_0.3,0.257549,0.352132,0.374676,0.419842,0.421878,0.436132
7,mlp_experience_replay_RR_0.3_PR_0.10,0.258759,0.349569,0.390708,0.424471,0.423675,0.422488
8,mlp_experience_replay_RR_0.3_PR_0.15,0.267114,0.352906,0.381841,0.418873,0.417310,0.397926
9,mlp_experience_replay_RR_0.4,0.261505,0.354953,0.390947,0.411936,0.426302,0.426986
10,mlp_experience_replay_RR_0.4_PR_0.10,0.270914,0.360895,0.392487,0.425705,0.430725,0.428381
11,mlp_experience_replay_RR_0.4_PR_0.15,0.270914,0.360959,0.393136,0.424377,0.422765,0.430864
12,mlp_experience_replay_RR_0.5,0.266522,0.354536,0.395463,0.424017,0.429688,0.432235
13,mlp_experience_replay_RR_0.5_PR_0.15,0.264416,0.354770,0.389014,0.423351,0.424573,0.429171
14,mlp_experience_replay_confidently_correct_memo...,0.254553,0.340999,0.387014,0.420529,0.414993,0.416860
15,mlp_experience_replay_confidently_correct_memo...,0.254553,0.350605,0.387633,0.415963,0.431255,0.403914
16,mlp_experience_replay_confidently_correct_memo...,0.270914,0.353986,0.386383,0.419062,0.412948,0.413548
17,mlp_experience_replay_confidently_correct_memo...,0.264416,0.347381,0.383941,0.412815,0.425174,0.414076
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.254553,0.304309,0.272887,0.326277,0.359044,0.348390
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.267114,0.332365,0.287267,0.356219,0.381936,0.413400
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.270914,0.333342,0.340238,0.357339,0.394228,0.398504
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.264416,0.354909,0.341410,0.390653,0.370733,0.370264
22,mlp_experience_replay_uncertainity_prioritizat...,0.262993,0.360492,0.394578,0.427579,0.436250,0.444105
23,mlp_experience_replay_uncertainity_prioritizat...,0.257549,0.361166,0.400459,0.426394,0.430350,0.448283
24,mlp_misclassification_buffer_RR_0.3,0.262993,0.322421,0.340021,0.367380,0.332941,0.408217
25,neighbours,0.187932,0.228379,0.200191,0.210693,0.211310,0.188561
26,prevyears_monthly_features,0.180581,0.229642,0.180678,0.247201,0.264105,0.312172
27,prevyears_monthly_features_experience_replay,0.187821,0.300985,0.310031,0.323793,0.332587,0.278506
28,prevyears_monthly_features_incremental_scaler,0.192974,0.284702,0.276791,0.308640,0.302494,0.352876
29,prevyears_monthly_features_incremental_scaler_...,0.186693,0.237786,0.271416,0.307426,0.305513,0.331957
30,sgd_experience_replay_RR_0.2,0.180836,0.250120,0.280705,0.339223,0.336539,0.359571
31,sgd_experience_replay_RR_0.3,0.196554,0.233705,0.286716,0.330193,0.345187,0.349783
32,sgd_experience_replay_RR_0.4,0.190390,0.229054,0.282267,0.324860,0.339634,0.349063
33,sgd_experience_replay_RR_0.5,0.197039,0.236470,0.275829,0.329374,0.337161,0.348419
34,prevyears_monthly_features_rbf,0.035619,0.039703,0.040013,0.039027,0.040208,0.043736

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_cumulative_f1.csv

PR_AUC matrix

,row,2017,2018,2019,2020,2021,2022
0,baseline,0.102965,0.168207,0.158203,0.176352,0.157524,0.160390
1,lagged_features,0.109286,0.164759,0.195867,0.239131,0.240151,0.240611
2,lagged_features_incremental_scaler,0.121508,0.219721,0.209383,0.240511,0.251137,0.276014
3,mlp_prevyears_monthly_features_incremental_scaler,0.203730,0.282858,0.134671,0.176211,0.189589,0.153146
4,mlp_experience_replay_RR_0.2,0.194117,0.330080,0.356420,0.385887,0.394393,0.407066
5,mlp_experience_replay_RR_0.2_PR_0.15,0.193359,0.318925,0.356535,0.390863,0.393339,0.399331
6,mlp_experience_replay_RR_0.3,0.184205,0.330828,0.355590,0.380531,0.395125,0.406027
7,mlp_experience_replay_RR_0.3_PR_0.10,0.185111,0.319109,0.358476,0.393286,0.394234,0.404370
8,mlp_experience_replay_RR_0.3_PR_0.15,0.201416,0.322864,0.349366,0.384959,0.385091,0.390250
9,mlp_experience_replay_RR_0.4,0.195044,0.333641,0.356214,0.380103,0.399303,0.407644
10,mlp_experience_replay_RR_0.4_PR_0.10,0.199051,0.334195,0.363337,0.392671,0.403398,0.408757
11,mlp_experience_replay_RR_0.4_PR_0.15,0.199051,0.330294,0.362815,0.389649,0.398556,0.411664
12,mlp_experience_replay_RR_0.5,0.197084,0.324276,0.365494,0.393231,0.401671,0.406419
13,mlp_experience_replay_RR_0.5_PR_0.15,0.193524,0.326667,0.354249,0.390071,0.395786,0.408552
14,mlp_experience_replay_confidently_correct_memo...,0.193359,0.314307,0.358772,0.384409,0.392159,0.397453
15,mlp_experience_replay_confidently_correct_memo...,0.193359,0.326684,0.358191,0.386531,0.395836,0.411123
16,mlp_experience_replay_confidently_correct_memo...,0.199051,0.330491,0.358396,0.386384,0.396456,0.398792
17,mlp_experience_replay_confidently_correct_memo...,0.193524,0.313615,0.353594,0.375641,0.392717,0.408066
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.193359,0.290049,0.238507,0.281878,0.322376,0.343504
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.201416,0.306546,0.254077,0.314188,0.351579,0.374493
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.199051,0.321626,0.304077,0.318045,0.351703,0.351573
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.193524,0.326530,0.310372,0.353275,0.341155,0.349762
22,mlp_experience_replay_uncertainity_prioritizat...,0.203925,0.329083,0.366491,0.394038,0.399981,0.412093
23,mlp_experience_replay_uncertainity_prioritizat...,0.184205,0.329351,0.370347,0.401397,0.412014,0.423135
24,mlp_misclassification_buffer_RR_0.3,0.203925,0.276886,0.308936,0.326587,0.306507,0.359200
25,neighbours,0.111358,0.179722,0.142986,0.149500,0.138072,0.125691
26,prevyears_monthly_features,0.105772,0.179791,0.110691,0.170084,0.178820,0.250445
27,prevyears_monthly_features_experience_replay,0.104466,0.250667,0.245701,0.254339,0.266558,0.300546
28,prevyears_monthly_features_incremental_scaler,0.112571,0.235183,0.217817,0.250886,0.262087,0.290641
29,prevyears_monthly_features_incremental_scaler_...,0.105441,0.191775,0.206850,0.244888,0.232170,0.275037
30,sgd_experience_replay_RR_0.2,0.096443,0.204138,0.213810,0.288782,0.304497,0.312657
31,sgd_experience_replay_RR_0.3,0.107887,0.188806,0.223300,0.277054,0.300476,0.304058
32,sgd_experience_replay_RR_0.4,0.105767,0.181091,0.220093,0.268404,0.299099,0.299021
33,sgd_experience_replay_RR_0.5,0.109380,0.190224,0.211855,0.277096,0.288173,0.299309
34,prevyears_monthly_features_rbf,0.017331,0.017914,0.018424,0.020833,0.020135,0.021570

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_cumulative_pr_auc.csv

====================================================================================================
TABLE: final_model_each_year
Rows are family_id. Columns are evaluation years.
Duplicate family-year rows are reduced using mean across contributing rows.
====================================================================================================

F1 matrix

,row,2017,2018,2019,2020,2021,2022
0,mlp_prevyears_monthly_features_incremental_scaler,0.150726,0.181082,0.448506,0.489963,0.446812,0.473149
1,mlp_experience_replay_RR_0.2,0.224603,0.433717,0.453624,0.489852,0.462159,0.493281
2,mlp_experience_replay_RR_0.2_PR_0.15,0.231486,0.437947,0.460876,0.501897,0.473289,0.475977
3,mlp_experience_replay_RR_0.3,0.241057,0.442076,0.449680,0.489239,0.450895,0.472905
4,mlp_experience_replay_RR_0.3_PR_0.10,0.240485,0.439333,0.462606,0.496699,0.459576,0.478229
5,mlp_experience_replay_RR_0.3_PR_0.15,0.227659,0.428677,0.459732,0.499744,0.477289,0.480458
6,mlp_experience_replay_RR_0.4,0.248817,0.435882,0.447548,0.490654,0.465240,0.469834
7,mlp_experience_replay_RR_0.4_PR_0.10,0.242238,0.440651,0.470286,0.492706,0.470349,0.484380
8,mlp_experience_replay_RR_0.4_PR_0.15,0.253746,0.446967,0.455965,0.492716,0.464584,0.483486
9,mlp_experience_replay_RR_0.5,0.248945,0.437448,0.450124,0.484390,0.460350,0.461663
10,mlp_experience_replay_RR_0.5_PR_0.15,0.229654,0.432011,0.467855,0.491720,0.469760,0.485432
11,mlp_experience_replay_confidently_correct_memo...,0.222204,0.414463,0.466465,0.500833,0.468961,0.481567
12,mlp_experience_replay_confidently_correct_memo...,0.252537,0.436801,0.475876,0.497236,0.473653,0.472664
13,mlp_experience_replay_confidently_correct_memo...,0.251638,0.441517,0.457208,0.488792,0.465656,0.471373
14,mlp_experience_replay_confidently_correct_memo...,0.235278,0.441006,0.465100,0.495334,0.465190,0.475926
15,mlp_experience_replay_hard_example_mining_RR_0.2,0.107186,0.274388,0.461966,0.487664,0.463359,0.476366
16,mlp_experience_replay_hard_example_mining_RR_0.3,0.159710,0.373752,0.458284,0.496696,0.471606,0.480506
17,mlp_experience_replay_hard_example_mining_RR_0.4,0.149241,0.276719,0.460498,0.458530,0.462913,0.483565
18,mlp_experience_replay_hard_example_mining_RR_0.5,0.118634,0.314018,0.466205,0.496544,0.469027,0.477990
19,mlp_experience_replay_uncertainity_prioritizat...,0.251637,0.445489,0.471998,0.494555,0.484009,0.466181
20,mlp_experience_replay_uncertainity_prioritizat...,0.257686,0.446976,0.473876,0.503500,0.478900,0.480314
21,mlp_misclassification_buffer_RR_0.3,0.085914,0.425968,0.437657,0.457917,0.444840,0.492810
22,prevyears_monthly_features_experience_replay,0.162581,0.346798,0.396538,0.425784,0.399305,0.416170
23,prevyears_monthly_features_incremental_scaler,0.162130,0.348546,0.398417,0.430781,0.397085,0.420131
24,prevyears_monthly_features_incremental_scaler_...,0.179674,0.364868,0.386105,0.410012,0.385430,0.399650
25,sgd_experience_replay_RR_0.5,0.182074,0.373849,0.388544,0.419177,0.388282,0.404232
26,prevyears_monthly_features_rbf,0.035629,0.040689,0.040496,0.051361,0.033256,0.061141

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_final_model_each_year_f1.csv

PR_AUC matrix

,row,2017,2018,2019,2020,2021,2022
0,mlp_prevyears_monthly_features_incremental_scaler,0.078806,0.108023,0.388679,0.458508,0.407686,0.454931
1,mlp_experience_replay_RR_0.2,0.155438,0.422557,0.409945,0.458534,0.430059,0.472962
2,mlp_experience_replay_RR_0.2_PR_0.15,0.154271,0.427455,0.417909,0.470253,0.438639,0.455022
3,mlp_experience_replay_RR_0.3,0.173606,0.441162,0.403056,0.459662,0.423617,0.452903
4,mlp_experience_replay_RR_0.3_PR_0.10,0.162300,0.432119,0.420626,0.467609,0.425877,0.457294
5,mlp_experience_replay_RR_0.3_PR_0.15,0.153024,0.417023,0.420012,0.467665,0.442473,0.453089
6,mlp_experience_replay_RR_0.4,0.183954,0.426867,0.406890,0.463793,0.430568,0.458092
7,mlp_experience_replay_RR_0.4_PR_0.10,0.170344,0.433007,0.428516,0.463220,0.434833,0.462808
8,mlp_experience_replay_RR_0.4_PR_0.15,0.192318,0.441547,0.417878,0.465612,0.436213,0.463495
9,mlp_experience_replay_RR_0.5,0.182041,0.428568,0.413712,0.452173,0.432244,0.451441
10,mlp_experience_replay_RR_0.5_PR_0.15,0.160794,0.423427,0.421378,0.467775,0.438859,0.466948
11,mlp_experience_replay_confidently_correct_memo...,0.148382,0.403045,0.409574,0.464406,0.430163,0.464229
12,mlp_experience_replay_confidently_correct_memo...,0.203734,0.426941,0.432417,0.467463,0.437179,0.462309
13,mlp_experience_replay_confidently_correct_memo...,0.182259,0.429665,0.411997,0.455198,0.429652,0.453179
14,mlp_experience_replay_confidently_correct_memo...,0.167709,0.429055,0.422260,0.466558,0.437611,0.466160
15,mlp_experience_replay_hard_example_mining_RR_0.2,0.056223,0.221334,0.426822,0.455262,0.423364,0.474515
16,mlp_experience_replay_hard_example_mining_RR_0.3,0.088078,0.336446,0.415755,0.463620,0.431548,0.478690
17,mlp_experience_replay_hard_example_mining_RR_0.4,0.082229,0.231078,0.419475,0.432621,0.427389,0.471639
18,mlp_experience_replay_hard_example_mining_RR_0.5,0.059818,0.244846,0.425019,0.463890,0.431746,0.459895
19,mlp_experience_replay_uncertainity_prioritizat...,0.172727,0.434311,0.425061,0.465918,0.445364,0.446195
20,mlp_experience_replay_uncertainity_prioritizat...,0.194138,0.439962,0.433673,0.472891,0.456998,0.463931
21,mlp_misclassification_buffer_RR_0.3,0.044570,0.390983,0.388780,0.431391,0.403180,0.472778
22,prevyears_monthly_features_experience_replay,0.085825,0.332732,0.351281,0.396565,0.372886,0.397788
23,prevyears_monthly_features_incremental_scaler,0.084545,0.332065,0.354247,0.403411,0.370796,0.401422
24,prevyears_monthly_features_incremental_scaler_...,0.105397,0.342351,0.339520,0.375780,0.358094,0.376471
25,sgd_experience_replay_RR_0.5,0.106972,0.352264,0.340746,0.382089,0.363753,0.378073
26,prevyears_monthly_features_rbf,0.016984,0.019534,0.018757,0.029362,0.016832,0.029462

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_final_model_each_year_pr_auc.csv

====================================================================================================
TABLE SECTION: prior_years (per model year)
Each table is one model year. Rows are family_id. Columns are eval_year <= model_year.
====================================================================================================

----------------------------------------------------------------------------------------------------
PRIOR MODEL YEAR: 2017
----------------------------------------------------------------------------------------------------

F1 matrix

                                                  row      2017
0                                            baseline  0.181211
1                                     lagged_features  0.183724
2                  lagged_features_incremental_scaler  0.199615
3   mlp_prevyears_monthly_features_incremental_scaler  0.263363
4                        mlp_experience_replay_RR_0.2  0.253968
5                mlp_experience_replay_RR_0.2_PR_0.15  0.254553
6                        mlp_experience_replay_RR_0.3  0.257549
7                mlp_experience_replay_RR_0.3_PR_0.10  0.258759
8                mlp_experience_replay_RR_0.3_PR_0.15  0.267114
9                        mlp_experience_replay_RR_0.4  0.261505
10               mlp_experience_replay_RR_0.4_PR_0.10  0.270914
11               mlp_experience_replay_RR_0.4_PR_0.15  0.270914
12                       mlp_experience_replay_RR_0.5  0.266522
13               mlp_experience_replay_RR_0.5_PR_0.15  0.264416
14  mlp_experience_replay_confidently_correct_memo...  0.254553
15  mlp_experience_replay_confidently_correct_memo...  0.254553
16  mlp_experience_replay_confidently_correct_memo...  0.270914
17  mlp_experience_replay_confidently_correct_memo...  0.264416
18   mlp_experience_replay_hard_example_mining_RR_0.2  0.254553
19   mlp_experience_replay_hard_example_mining_RR_0.3  0.267114
20   mlp_experience_replay_hard_example_mining_RR_0.4  0.270914
21   mlp_experience_replay_hard_example_mining_RR_0.5  0.264416
22  mlp_experience_replay_uncertainity_prioritizat...  0.262993
23  mlp_experience_replay_uncertainity_prioritizat...  0.257549
24                mlp_misclassification_buffer_RR_0.3  0.262993
25                                         neighbours  0.187932
26                         prevyears_monthly_features  0.180581
27       prevyears_monthly_features_experience_replay  0.187821
28      prevyears_monthly_features_incremental_scaler  0.192974
29  prevyears_monthly_features_incremental_scaler_...  0.186693
30                       sgd_experience_replay_RR_0.2  0.180836
31                       sgd_experience_replay_RR_0.3  0.196554
32                       sgd_experience_replay_RR_0.4  0.190390
33                       sgd_experience_replay_RR_0.5  0.197039
34                     prevyears_monthly_features_rbf  0.035619

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2017_f1.csv

PR_AUC matrix

                                                  row      2017
0                                            baseline  0.102965
1                                     lagged_features  0.109286
2                  lagged_features_incremental_scaler  0.121508
3   mlp_prevyears_monthly_features_incremental_scaler  0.203730
4                        mlp_experience_replay_RR_0.2  0.194117
5                mlp_experience_replay_RR_0.2_PR_0.15  0.193359
6                        mlp_experience_replay_RR_0.3  0.184205
7                mlp_experience_replay_RR_0.3_PR_0.10  0.185111
8                mlp_experience_replay_RR_0.3_PR_0.15  0.201416
9                        mlp_experience_replay_RR_0.4  0.195044
10               mlp_experience_replay_RR_0.4_PR_0.10  0.199051
11               mlp_experience_replay_RR_0.4_PR_0.15  0.199051
12                       mlp_experience_replay_RR_0.5  0.197084
13               mlp_experience_replay_RR_0.5_PR_0.15  0.193524
14  mlp_experience_replay_confidently_correct_memo...  0.193359
15  mlp_experience_replay_confidently_correct_memo...  0.193359
16  mlp_experience_replay_confidently_correct_memo...  0.199051
17  mlp_experience_replay_confidently_correct_memo...  0.193524
18   mlp_experience_replay_hard_example_mining_RR_0.2  0.193359
19   mlp_experience_replay_hard_example_mining_RR_0.3  0.201416
20   mlp_experience_replay_hard_example_mining_RR_0.4  0.199051
21   mlp_experience_replay_hard_example_mining_RR_0.5  0.193524
22  mlp_experience_replay_uncertainity_prioritizat...  0.203925
23  mlp_experience_replay_uncertainity_prioritizat...  0.184205
24                mlp_misclassification_buffer_RR_0.3  0.203925
25                                         neighbours  0.111358
26                         prevyears_monthly_features  0.105772
27       prevyears_monthly_features_experience_replay  0.104466
28      prevyears_monthly_features_incremental_scaler  0.112571
29  prevyears_monthly_features_incremental_scaler_...  0.105441
30                       sgd_experience_replay_RR_0.2  0.096443
31                       sgd_experience_replay_RR_0.3  0.107887
32                       sgd_experience_replay_RR_0.4  0.105767
33                       sgd_experience_replay_RR_0.5  0.109380
34                     prevyears_monthly_features_rbf  0.017331

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2017_pr_auc.csv

----------------------------------------------------------------------------------------------------
PRIOR MODEL YEAR: 2018
----------------------------------------------------------------------------------------------------

F1 matrix

                                                  row      2017      2018
0                                            baseline  0.162611  0.394452
1                                     lagged_features  0.160845  0.394536
2                  lagged_features_incremental_scaler  0.159906  0.395409
3   mlp_prevyears_monthly_features_incremental_scaler  0.162795  0.450257
4                        mlp_experience_replay_RR_0.2  0.240061  0.449656
5                mlp_experience_replay_RR_0.2_PR_0.15  0.242755  0.443568
6                        mlp_experience_replay_RR_0.3  0.247786  0.452124
7                mlp_experience_replay_RR_0.3_PR_0.10  0.245595  0.443730
8                mlp_experience_replay_RR_0.3_PR_0.15  0.249459  0.445327
9                        mlp_experience_replay_RR_0.4  0.253993  0.450813
10               mlp_experience_replay_RR_0.4_PR_0.10  0.253969  0.450734
11               mlp_experience_replay_RR_0.4_PR_0.15  0.248052  0.456370
12                       mlp_experience_replay_RR_0.5  0.247869  0.445370
13               mlp_experience_replay_RR_0.5_PR_0.15  0.247863  0.452978
14  mlp_experience_replay_confidently_correct_memo...  0.231410  0.446245
15  mlp_experience_replay_confidently_correct_memo...  0.248317  0.442857
16  mlp_experience_replay_confidently_correct_memo...  0.251715  0.446613
17  mlp_experience_replay_confidently_correct_memo...  0.241447  0.448491
18   mlp_experience_replay_hard_example_mining_RR_0.2  0.155512  0.442323
19   mlp_experience_replay_hard_example_mining_RR_0.3  0.195178  0.449884
20   mlp_experience_replay_hard_example_mining_RR_0.4  0.216730  0.454317
21   mlp_experience_replay_hard_example_mining_RR_0.5  0.234736  0.456053
22  mlp_experience_replay_uncertainity_prioritizat...  0.255316  0.446449
23  mlp_experience_replay_uncertainity_prioritizat...  0.257775  0.450579
24                mlp_misclassification_buffer_RR_0.3  0.121800  0.446174
25                                         neighbours  0.167140  0.395161
26                         prevyears_monthly_features  0.174335  0.405588
27       prevyears_monthly_features_experience_replay  0.175181  0.409010
28      prevyears_monthly_features_incremental_scaler  0.171684  0.412624
29  prevyears_monthly_features_incremental_scaler_...  0.187086  0.396712
30                       sgd_experience_replay_RR_0.2  0.187698  0.404282
31                       sgd_experience_replay_RR_0.3  0.188078  0.400056
32                       sgd_experience_replay_RR_0.4  0.182679  0.399406
33                       sgd_experience_replay_RR_0.5  0.187189  0.396026
34                     prevyears_monthly_features_rbf  0.034397  0.043850

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2018_f1.csv

PR_AUC matrix

                                                  row      2017      2018
0                                            baseline  0.098798  0.379073
1                                     lagged_features  0.094862  0.378105
2                  lagged_features_incremental_scaler  0.093915  0.375879
3   mlp_prevyears_monthly_features_incremental_scaler  0.085506  0.444538
4                        mlp_experience_replay_RR_0.2  0.166130  0.442351
5                mlp_experience_replay_RR_0.2_PR_0.15  0.165013  0.429477
6                        mlp_experience_replay_RR_0.3  0.172288  0.441084
7                mlp_experience_replay_RR_0.3_PR_0.10  0.171133  0.433883
8                mlp_experience_replay_RR_0.3_PR_0.15  0.171652  0.437488
9                        mlp_experience_replay_RR_0.4  0.176140  0.443769
10               mlp_experience_replay_RR_0.4_PR_0.10  0.181804  0.444792
11               mlp_experience_replay_RR_0.4_PR_0.15  0.173161  0.447425
12                       mlp_experience_replay_RR_0.5  0.174520  0.433662
13               mlp_experience_replay_RR_0.5_PR_0.15  0.175204  0.443333
14  mlp_experience_replay_confidently_correct_memo...  0.156221  0.439391
15  mlp_experience_replay_confidently_correct_memo...  0.171132  0.438024
16  mlp_experience_replay_confidently_correct_memo...  0.183301  0.440433
17  mlp_experience_replay_confidently_correct_memo...  0.168691  0.437585
18   mlp_experience_replay_hard_example_mining_RR_0.2  0.092846  0.435702
19   mlp_experience_replay_hard_example_mining_RR_0.3  0.118379  0.440620
20   mlp_experience_replay_hard_example_mining_RR_0.4  0.143274  0.443491
21   mlp_experience_replay_hard_example_mining_RR_0.5  0.164475  0.443531
22  mlp_experience_replay_uncertainity_prioritizat...  0.189931  0.438872
23  mlp_experience_replay_uncertainity_prioritizat...  0.178612  0.437642
24                mlp_misclassification_buffer_RR_0.3  0.073442  0.436951
25                                         neighbours  0.106872  0.383249
26                         prevyears_monthly_features  0.105739  0.389604
27       prevyears_monthly_features_experience_replay  0.106675  0.395264
28      prevyears_monthly_features_incremental_scaler  0.100661  0.395498
29  prevyears_monthly_features_incremental_scaler_...  0.115800  0.381160
30                       sgd_experience_replay_RR_0.2  0.117317  0.391483
31                       sgd_experience_replay_RR_0.3  0.118349  0.383693
32                       sgd_experience_replay_RR_0.4  0.113970  0.379016
33                       sgd_experience_replay_RR_0.5  0.116412  0.377575
34                     prevyears_monthly_features_rbf  0.016715  0.019169

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2018_pr_auc.csv

----------------------------------------------------------------------------------------------------
PRIOR MODEL YEAR: 2019
----------------------------------------------------------------------------------------------------

F1 matrix

,row,2017,2018,2019
0,baseline,0.186985,0.249698,0.218509
1,lagged_features,0.171605,0.376337,0.393827
2,lagged_features_incremental_scaler,0.174841,0.372814,0.394097
3,mlp_prevyears_monthly_features_incremental_scaler,0.063737,0.382317,0.468561
4,mlp_experience_replay_RR_0.2,0.232452,0.431265,0.468287
5,mlp_experience_replay_RR_0.2_PR_0.15,0.228960,0.434071,0.476202
6,mlp_experience_replay_RR_0.3,0.249580,0.444024,0.470972
7,mlp_experience_replay_RR_0.3_PR_0.10,0.253507,0.429218,0.461814
8,mlp_experience_replay_RR_0.3_PR_0.15,0.221972,0.435185,0.465927
9,mlp_experience_replay_RR_0.4,0.244597,0.432498,0.462095
10,mlp_experience_replay_RR_0.4_PR_0.10,0.245601,0.449614,0.467719
11,mlp_experience_replay_RR_0.4_PR_0.15,0.250097,0.440857,0.476596
12,mlp_experience_replay_RR_0.5,0.248756,0.432007,0.475107
13,mlp_experience_replay_RR_0.5_PR_0.15,0.244557,0.438933,0.462227
14,mlp_experience_replay_confidently_correct_memo...,0.251517,0.431907,0.475236
15,mlp_experience_replay_confidently_correct_memo...,0.236515,0.433657,0.466787
16,mlp_experience_replay_confidently_correct_memo...,0.242900,0.436020,0.465934
17,mlp_experience_replay_confidently_correct_memo...,0.254079,0.429620,0.468250
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.101543,0.270155,0.466492
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.139848,0.295311,0.465055
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.183981,0.408235,0.466153
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.185462,0.385379,0.470489
22,mlp_experience_replay_uncertainity_prioritizat...,0.264940,0.443531,0.468904
23,mlp_experience_replay_uncertainity_prioritizat...,0.260061,0.453988,0.473401
24,mlp_misclassification_buffer_RR_0.3,0.189991,0.392565,0.470635
25,neighbours,0.182418,0.262417,0.185108
26,prevyears_monthly_features,0.113525,0.235389,0.417279
27,prevyears_monthly_features_experience_replay,0.174809,0.366389,0.409905
28,prevyears_monthly_features_incremental_scaler,0.176729,0.389915,0.411193
29,prevyears_monthly_features_incremental_scaler_...,0.187993,0.390586,0.401195
30,sgd_experience_replay_RR_0.2,0.185978,0.385994,0.402829
31,sgd_experience_replay_RR_0.3,0.185688,0.387510,0.403886
32,sgd_experience_replay_RR_0.4,0.185317,0.389383,0.399413
33,sgd_experience_replay_RR_0.5,0.186977,0.386633,0.400979
34,prevyears_monthly_features_rbf,0.035627,0.043832,0.040473

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2019_f1.csv

PR_AUC matrix

,row,2017,2018,2019
0,baseline,0.123315,0.187019,0.160839
1,lagged_features,0.094197,0.350686,0.343162
2,lagged_features_incremental_scaler,0.096678,0.342506,0.341089
3,mlp_prevyears_monthly_features_incremental_scaler,0.031835,0.335422,0.425024
4,mlp_experience_replay_RR_0.2,0.161731,0.423737,0.431550
5,mlp_experience_replay_RR_0.2_PR_0.15,0.153598,0.420747,0.438943
6,mlp_experience_replay_RR_0.3,0.169935,0.437397,0.431101
7,mlp_experience_replay_RR_0.3_PR_0.10,0.187611,0.423174,0.422023
8,mlp_experience_replay_RR_0.3_PR_0.15,0.146794,0.424203,0.421863
9,mlp_experience_replay_RR_0.4,0.179097,0.414466,0.427322
10,mlp_experience_replay_RR_0.4_PR_0.10,0.172568,0.436345,0.429570
11,mlp_experience_replay_RR_0.4_PR_0.15,0.186339,0.428990,0.438333
12,mlp_experience_replay_RR_0.5,0.172100,0.429650,0.439158
13,mlp_experience_replay_RR_0.5_PR_0.15,0.158965,0.422279,0.425234
14,mlp_experience_replay_confidently_correct_memo...,0.177307,0.420604,0.436605
15,mlp_experience_replay_confidently_correct_memo...,0.173808,0.431430,0.424983
16,mlp_experience_replay_confidently_correct_memo...,0.178166,0.428047,0.428609
17,mlp_experience_replay_confidently_correct_memo...,0.181447,0.412567,0.432147
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.053563,0.179695,0.420814
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.076337,0.229050,0.420219
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.114838,0.372025,0.426746
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.105822,0.327531,0.427612
22,mlp_experience_replay_uncertainity_prioritizat...,0.186830,0.431528,0.433359
23,mlp_experience_replay_uncertainity_prioritizat...,0.187240,0.443709,0.432481
24,mlp_misclassification_buffer_RR_0.3,0.109923,0.365425,0.423470
25,neighbours,0.120030,0.197279,0.120917
26,prevyears_monthly_features,0.058897,0.157231,0.363116
27,prevyears_monthly_features_experience_replay,0.092646,0.326694,0.355973
28,prevyears_monthly_features_incremental_scaler,0.095632,0.362957,0.359045
29,prevyears_monthly_features_incremental_scaler_...,0.109993,0.359422,0.343636
30,sgd_experience_replay_RR_0.2,0.106846,0.354804,0.347802
31,sgd_experience_replay_RR_0.3,0.107212,0.359026,0.348980
32,sgd_experience_replay_RR_0.4,0.106587,0.361412,0.347437
33,sgd_experience_replay_RR_0.5,0.107736,0.358625,0.346834
34,prevyears_monthly_features_rbf,0.017040,0.019188,0.019136

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2019_pr_auc.csv

----------------------------------------------------------------------------------------------------
PRIOR MODEL YEAR: 2020
----------------------------------------------------------------------------------------------------

F1 matrix

,row,2017,2018,2019,2020
0,baseline,0.193296,0.291724,0.213457,0.256754
1,lagged_features,0.174388,0.378457,0.387005,0.419739
2,lagged_features_incremental_scaler,0.172378,0.373951,0.384915,0.412271
3,mlp_prevyears_monthly_features_incremental_scaler,0.168036,0.283029,0.457197,0.486295
4,mlp_experience_replay_RR_0.2,0.242542,0.433641,0.468617,0.493626
5,mlp_experience_replay_RR_0.2_PR_0.15,0.246992,0.442419,0.471831,0.484972
6,mlp_experience_replay_RR_0.3,0.254558,0.440507,0.459572,0.492685
7,mlp_experience_replay_RR_0.3_PR_0.10,0.247675,0.446225,0.474621,0.491207
8,mlp_experience_replay_RR_0.3_PR_0.15,0.240430,0.445254,0.475960,0.484842
9,mlp_experience_replay_RR_0.4,0.238107,0.433633,0.458594,0.484699
10,mlp_experience_replay_RR_0.4_PR_0.10,0.250252,0.448438,0.477864,0.496405
11,mlp_experience_replay_RR_0.4_PR_0.15,0.235025,0.447617,0.478720,0.491154
12,mlp_experience_replay_RR_0.5,0.242035,0.447675,0.474390,0.497112
13,mlp_experience_replay_RR_0.5_PR_0.15,0.248871,0.446094,0.465278,0.494093
14,mlp_experience_replay_confidently_correct_memo...,0.249814,0.435386,0.483385,0.487451
15,mlp_experience_replay_confidently_correct_memo...,0.248262,0.436527,0.469126,0.483842
16,mlp_experience_replay_confidently_correct_memo...,0.249987,0.446578,0.470485,0.483531
17,mlp_experience_replay_confidently_correct_memo...,0.238310,0.437424,0.458518,0.491770
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.098501,0.229920,0.460736,0.480815
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.136329,0.306270,0.458333,0.501752
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.132710,0.358517,0.440241,0.492846
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.146829,0.389580,0.457902,0.492516
22,mlp_experience_replay_uncertainity_prioritizat...,0.261614,0.451663,0.468455,0.489940
23,mlp_experience_replay_uncertainity_prioritizat...,0.257602,0.458470,0.474371,0.492213
24,mlp_misclassification_buffer_RR_0.3,0.097992,0.419444,0.462127,0.484667
25,neighbours,0.181359,0.291999,0.171640,0.214480
26,prevyears_monthly_features,0.131837,0.285201,0.408633,0.446585
27,prevyears_monthly_features_experience_replay,0.143085,0.308907,0.406586,0.439004
28,prevyears_monthly_features_incremental_scaler,0.176015,0.389904,0.404593,0.437638
29,prevyears_monthly_features_incremental_scaler_...,0.192351,0.385450,0.398016,0.431044
30,sgd_experience_replay_RR_0.2,0.191430,0.387840,0.388570,0.429426
31,sgd_experience_replay_RR_0.3,0.189663,0.390777,0.393255,0.430640
32,sgd_experience_replay_RR_0.4,0.187303,0.389965,0.395867,0.432000
33,sgd_experience_replay_RR_0.5,0.191540,0.389382,0.397988,0.441788
34,prevyears_monthly_features_rbf,0.035567,0.039243,0.040511,0.053503

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2020_f1.csv

PR_AUC matrix

,row,2017,2018,2019,2020
0,baseline,0.126380,0.254569,0.149592,0.193445
1,lagged_features,0.104351,0.361825,0.341201,0.385600
2,lagged_features_incremental_scaler,0.101135,0.354823,0.338693,0.376934
3,mlp_prevyears_monthly_features_incremental_scaler,0.092714,0.220707,0.406734,0.454080
4,mlp_experience_replay_RR_0.2,0.174500,0.421029,0.428878,0.467488
5,mlp_experience_replay_RR_0.2_PR_0.15,0.179080,0.431709,0.429556,0.454944
6,mlp_experience_replay_RR_0.3,0.181569,0.419344,0.417189,0.451725
7,mlp_experience_replay_RR_0.3_PR_0.10,0.173561,0.437885,0.435413,0.455221
8,mlp_experience_replay_RR_0.3_PR_0.15,0.184180,0.434344,0.428819,0.452702
9,mlp_experience_replay_RR_0.4,0.154275,0.418471,0.422794,0.453357
10,mlp_experience_replay_RR_0.4_PR_0.10,0.173806,0.432498,0.437616,0.461238
11,mlp_experience_replay_RR_0.4_PR_0.15,0.170067,0.443954,0.436431,0.448996
12,mlp_experience_replay_RR_0.5,0.177319,0.435896,0.436773,0.464704
13,mlp_experience_replay_RR_0.5_PR_0.15,0.178944,0.433475,0.425879,0.454551
14,mlp_experience_replay_confidently_correct_memo...,0.180992,0.415643,0.435958,0.457256
15,mlp_experience_replay_confidently_correct_memo...,0.184183,0.425738,0.424726,0.454236
16,mlp_experience_replay_confidently_correct_memo...,0.172723,0.433352,0.428900,0.447677
17,mlp_experience_replay_confidently_correct_memo...,0.171062,0.419285,0.415721,0.455378
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.051129,0.157892,0.419261,0.445869
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.072865,0.260594,0.411620,0.470023
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.079874,0.312815,0.391089,0.459915
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.116772,0.352087,0.416367,0.461833
22,mlp_experience_replay_uncertainity_prioritizat...,0.184031,0.440396,0.424539,0.460230
23,mlp_experience_replay_uncertainity_prioritizat...,0.198040,0.450105,0.426729,0.467084
24,mlp_misclassification_buffer_RR_0.3,0.050873,0.391241,0.413606,0.463117
25,neighbours,0.115714,0.250511,0.121662,0.152466
26,prevyears_monthly_features,0.070423,0.221401,0.363268,0.412449
27,prevyears_monthly_features_experience_replay,0.075452,0.255036,0.350530,0.403962
28,prevyears_monthly_features_incremental_scaler,0.099413,0.368519,0.352552,0.403619
29,prevyears_monthly_features_incremental_scaler_...,0.116674,0.367272,0.337634,0.388120
30,sgd_experience_replay_RR_0.2,0.116437,0.371091,0.339997,0.391189
31,sgd_experience_replay_RR_0.3,0.115520,0.371379,0.341063,0.393052
32,sgd_experience_replay_RR_0.4,0.114436,0.370528,0.342535,0.394471
33,sgd_experience_replay_RR_0.5,0.120632,0.370926,0.345766,0.404802
34,prevyears_monthly_features_rbf,0.017010,0.018842,0.018978,0.029920

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2020_pr_auc.csv

----------------------------------------------------------------------------------------------------
PRIOR MODEL YEAR: 2021
----------------------------------------------------------------------------------------------------

F1 matrix

,row,2017,2018,2019,2020,2021
0,baseline,0.190423,0.240950,0.231401,0.226584,0.230862
1,lagged_features,0.162914,0.386418,0.397681,0.420537,0.408259
2,lagged_features_incremental_scaler,0.166228,0.366704,0.398554,0.418532,0.401910
3,mlp_prevyears_monthly_features_incremental_scaler,0.184486,0.070264,0.446333,0.506937,0.470570
4,mlp_experience_replay_RR_0.2,0.233082,0.431895,0.469094,0.501613,0.475431
5,mlp_experience_replay_RR_0.2_PR_0.15,0.225613,0.428574,0.479509,0.496017,0.476525
6,mlp_experience_replay_RR_0.3,0.246573,0.440526,0.469961,0.490151,0.475714
7,mlp_experience_replay_RR_0.3_PR_0.10,0.251561,0.435831,0.470379,0.496172,0.476782
8,mlp_experience_replay_RR_0.3_PR_0.15,0.229981,0.431457,0.462339,0.499630,0.477080
9,mlp_experience_replay_RR_0.4,0.237693,0.445149,0.461871,0.500072,0.470926
10,mlp_experience_replay_RR_0.4_PR_0.10,0.250443,0.448436,0.469686,0.499279,0.478935
11,mlp_experience_replay_RR_0.4_PR_0.15,0.234200,0.446557,0.475915,0.494706,0.468613
12,mlp_experience_replay_RR_0.5,0.246567,0.443866,0.469901,0.509140,0.473050
13,mlp_experience_replay_RR_0.5_PR_0.15,0.242537,0.441194,0.470081,0.501228,0.473355
14,mlp_experience_replay_confidently_correct_memo...,0.235369,0.433996,0.470178,0.494550,0.470918
15,mlp_experience_replay_confidently_correct_memo...,0.233460,0.429702,0.467566,0.507793,0.477130
16,mlp_experience_replay_confidently_correct_memo...,0.249164,0.435227,0.464382,0.496171,0.463485
17,mlp_experience_replay_confidently_correct_memo...,0.248635,0.435464,0.458768,0.498559,0.475783
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.119399,0.287484,0.447679,0.471765,0.466952
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.158130,0.380624,0.444857,0.490364,0.471366
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.167305,0.345675,0.462428,0.487362,0.481376
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.138514,0.327829,0.460145,0.494570,0.484973
22,mlp_experience_replay_uncertainity_prioritizat...,0.260974,0.450051,0.472983,0.500964,0.484355
23,mlp_experience_replay_uncertainity_prioritizat...,0.265479,0.454764,0.473398,0.503726,0.475155
24,mlp_misclassification_buffer_RR_0.3,0.147682,0.354365,0.458402,0.481185,0.462473
25,neighbours,0.188868,0.254467,0.204627,0.203332,0.198482
26,prevyears_monthly_features,0.131128,0.308442,0.420768,0.431733,0.407614
27,prevyears_monthly_features_experience_replay,0.149581,0.329783,0.413769,0.441682,0.404064
28,prevyears_monthly_features_incremental_scaler,0.171775,0.377852,0.420302,0.459458,0.413210
29,prevyears_monthly_features_incremental_scaler_...,0.185368,0.392859,0.404860,0.431615,0.390829
30,sgd_experience_replay_RR_0.2,0.184988,0.387651,0.401410,0.433783,0.390667
31,sgd_experience_replay_RR_0.3,0.182380,0.390437,0.407645,0.433209,0.404053
32,sgd_experience_replay_RR_0.4,0.184545,0.390473,0.404248,0.433844,0.396018
33,sgd_experience_replay_RR_0.5,0.183431,0.393268,0.403160,0.430106,0.399003
34,prevyears_monthly_features_rbf,0.035621,0.040435,0.040952,0.053543,0.033240

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2021_f1.csv

PR_AUC matrix

,row,2017,2018,2019,2020,2021
0,baseline,0.119223,0.185184,0.156432,0.167298,0.163037
1,lagged_features,0.093693,0.356552,0.346925,0.391330,0.395786
2,lagged_features_incremental_scaler,0.095085,0.330456,0.350503,0.387734,0.386522
3,mlp_prevyears_monthly_features_incremental_scaler,0.099679,0.036884,0.399185,0.473152,0.440404
4,mlp_experience_replay_RR_0.2,0.160464,0.423588,0.419619,0.466907,0.438441
5,mlp_experience_replay_RR_0.2_PR_0.15,0.156501,0.412120,0.427194,0.466999,0.440482
6,mlp_experience_replay_RR_0.3,0.163174,0.430673,0.421756,0.458798,0.439322
7,mlp_experience_replay_RR_0.3_PR_0.10,0.183092,0.416030,0.423092,0.469595,0.450059
8,mlp_experience_replay_RR_0.3_PR_0.15,0.141984,0.415940,0.411860,0.470918,0.449200
9,mlp_experience_replay_RR_0.4,0.171252,0.434485,0.421901,0.479891,0.437619
10,mlp_experience_replay_RR_0.4_PR_0.10,0.177404,0.440908,0.418376,0.468995,0.447627
11,mlp_experience_replay_RR_0.4_PR_0.15,0.149791,0.439186,0.431426,0.469922,0.437317
12,mlp_experience_replay_RR_0.5,0.177934,0.439727,0.422076,0.480126,0.447323
13,mlp_experience_replay_RR_0.5_PR_0.15,0.158502,0.431938,0.424943,0.467895,0.442718
14,mlp_experience_replay_confidently_correct_memo...,0.165235,0.421883,0.416475,0.457240,0.442651
15,mlp_experience_replay_confidently_correct_memo...,0.164326,0.417503,0.413349,0.477055,0.443492
16,mlp_experience_replay_confidently_correct_memo...,0.177162,0.425196,0.417750,0.462456,0.440395
17,mlp_experience_replay_confidently_correct_memo...,0.180297,0.423353,0.409307,0.458713,0.438188
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.057225,0.234076,0.401533,0.453775,0.431523
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.090800,0.333146,0.398144,0.464870,0.447988
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.097959,0.300343,0.410783,0.462380,0.450295
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.073836,0.255152,0.417515,0.464677,0.441211
22,mlp_experience_replay_uncertainity_prioritizat...,0.177656,0.437267,0.412954,0.464438,0.451228
23,mlp_experience_replay_uncertainity_prioritizat...,0.201513,0.447626,0.429767,0.475431,0.448151
24,mlp_misclassification_buffer_RR_0.3,0.076539,0.329506,0.406161,0.451948,0.432253
25,neighbours,0.116341,0.188878,0.128218,0.137662,0.128176
26,prevyears_monthly_features,0.068708,0.246731,0.365066,0.402027,0.382962
27,prevyears_monthly_features_experience_replay,0.079719,0.273964,0.355639,0.411117,0.385958
28,prevyears_monthly_features_incremental_scaler,0.094752,0.346449,0.367890,0.430190,0.391261
29,prevyears_monthly_features_incremental_scaler_...,0.107267,0.358908,0.349147,0.388614,0.358327
30,sgd_experience_replay_RR_0.2,0.108696,0.353845,0.355799,0.398796,0.365328
31,sgd_experience_replay_RR_0.3,0.107135,0.356874,0.358138,0.399232,0.376125
32,sgd_experience_replay_RR_0.4,0.109739,0.359309,0.356726,0.399757,0.373436
33,sgd_experience_replay_RR_0.5,0.107114,0.365423,0.354884,0.396551,0.367220
34,prevyears_monthly_features_rbf,0.017316,0.019152,0.019275,0.029475,0.016893

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2021_pr_auc.csv

----------------------------------------------------------------------------------------------------
PRIOR MODEL YEAR: 2022
----------------------------------------------------------------------------------------------------

F1 matrix

,row,2017,2018,2019,2020,2021,2022
0,baseline,0.176663,0.236311,0.204680,0.221384,0.207831,0.258414
1,lagged_features,0.158352,0.363753,0.389842,0.389340,0.399286,0.413103
2,lagged_features_incremental_scaler,0.157600,0.359747,0.390527,0.402285,0.386724,0.411766
3,mlp_prevyears_monthly_features_incremental_scaler,0.150726,0.181082,0.448506,0.489963,0.446812,0.473149
4,mlp_experience_replay_RR_0.2,0.224603,0.433717,0.453624,0.489852,0.462159,0.493281
5,mlp_experience_replay_RR_0.2_PR_0.15,0.231486,0.437947,0.460876,0.501897,0.473289,0.475977
6,mlp_experience_replay_RR_0.3,0.241057,0.442076,0.449680,0.489239,0.450895,0.472905
7,mlp_experience_replay_RR_0.3_PR_0.10,0.240485,0.439333,0.462606,0.496699,0.459576,0.478229
8,mlp_experience_replay_RR_0.3_PR_0.15,0.227659,0.428677,0.459732,0.499744,0.477289,0.480458
9,mlp_experience_replay_RR_0.4,0.248817,0.435882,0.447548,0.490654,0.465240,0.469834
10,mlp_experience_replay_RR_0.4_PR_0.10,0.242238,0.440651,0.470286,0.492706,0.470349,0.484380
11,mlp_experience_replay_RR_0.4_PR_0.15,0.253746,0.446967,0.455965,0.492716,0.464584,0.483486
12,mlp_experience_replay_RR_0.5,0.248945,0.437448,0.450124,0.484390,0.460350,0.461663
13,mlp_experience_replay_RR_0.5_PR_0.15,0.229654,0.432011,0.467855,0.491720,0.469760,0.485432
14,mlp_experience_replay_confidently_correct_memo...,0.222204,0.414463,0.466465,0.500833,0.468961,0.481567
15,mlp_experience_replay_confidently_correct_memo...,0.252537,0.436801,0.475876,0.497236,0.473653,0.472664
16,mlp_experience_replay_confidently_correct_memo...,0.251638,0.441517,0.457208,0.488792,0.465656,0.471373
17,mlp_experience_replay_confidently_correct_memo...,0.235278,0.441006,0.465100,0.495334,0.465190,0.475926
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.107186,0.274388,0.461966,0.487664,0.463359,0.476366
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.159710,0.373752,0.458284,0.496696,0.471606,0.480506
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.149241,0.276719,0.460498,0.458530,0.462913,0.483565
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.118634,0.314018,0.466205,0.496544,0.469027,0.477990
22,mlp_experience_replay_uncertainity_prioritizat...,0.251637,0.445489,0.471998,0.494555,0.484009,0.466181
23,mlp_experience_replay_uncertainity_prioritizat...,0.257686,0.446976,0.473876,0.503500,0.478900,0.480314
24,mlp_misclassification_buffer_RR_0.3,0.085914,0.425968,0.437657,0.457917,0.444840,0.492810
25,neighbours,0.166848,0.230557,0.174148,0.183790,0.172171,0.231862
26,prevyears_monthly_features,0.167729,0.376482,0.401107,0.421222,0.405427,0.415744
27,prevyears_monthly_features_experience_replay,0.162581,0.346798,0.396538,0.425784,0.399305,0.416170
28,prevyears_monthly_features_incremental_scaler,0.162130,0.348546,0.398417,0.430781,0.397085,0.420131
29,prevyears_monthly_features_incremental_scaler_...,0.179674,0.364868,0.386105,0.410012,0.385430,0.399650
30,sgd_experience_replay_RR_0.2,0.176007,0.366697,0.399264,0.417367,0.390960,0.407070
31,sgd_experience_replay_RR_0.3,0.178971,0.365236,0.391641,0.412647,0.387207,0.391797
32,sgd_experience_replay_RR_0.4,0.179002,0.366447,0.394695,0.411846,0.381107,0.396356
33,sgd_experience_replay_RR_0.5,0.182074,0.373849,0.388544,0.419177,0.388282,0.404232
34,prevyears_monthly_features_rbf,0.035629,0.040689,0.040496,0.051361,0.033256,0.061141

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2022_f1.csv

PR_AUC matrix

,row,2017,2018,2019,2020,2021,2022
0,baseline,0.114295,0.190124,0.148612,0.163078,0.147342,0.195861
1,lagged_features,0.086834,0.336067,0.337247,0.353612,0.372492,0.386227
2,lagged_features_incremental_scaler,0.085307,0.332058,0.339775,0.368690,0.368186,0.386627
3,mlp_prevyears_monthly_features_incremental_scaler,0.078806,0.108023,0.388679,0.458508,0.407686,0.454931
4,mlp_experience_replay_RR_0.2,0.155438,0.422557,0.409945,0.458534,0.430059,0.472962
5,mlp_experience_replay_RR_0.2_PR_0.15,0.154271,0.427455,0.417909,0.470253,0.438639,0.455022
6,mlp_experience_replay_RR_0.3,0.173606,0.441162,0.403056,0.459662,0.423617,0.452903
7,mlp_experience_replay_RR_0.3_PR_0.10,0.162300,0.432119,0.420626,0.467609,0.425877,0.457294
8,mlp_experience_replay_RR_0.3_PR_0.15,0.153024,0.417023,0.420012,0.467665,0.442473,0.453089
9,mlp_experience_replay_RR_0.4,0.183954,0.426867,0.406890,0.463793,0.430568,0.458092
10,mlp_experience_replay_RR_0.4_PR_0.10,0.170344,0.433007,0.428516,0.463220,0.434833,0.462808
11,mlp_experience_replay_RR_0.4_PR_0.15,0.192318,0.441547,0.417878,0.465612,0.436213,0.463495
12,mlp_experience_replay_RR_0.5,0.182041,0.428568,0.413712,0.452173,0.432244,0.451441
13,mlp_experience_replay_RR_0.5_PR_0.15,0.160794,0.423427,0.421378,0.467775,0.438859,0.466948
14,mlp_experience_replay_confidently_correct_memo...,0.148382,0.403045,0.409574,0.464406,0.430163,0.464229
15,mlp_experience_replay_confidently_correct_memo...,0.203734,0.426941,0.432417,0.467463,0.437179,0.462309
16,mlp_experience_replay_confidently_correct_memo...,0.182259,0.429665,0.411997,0.455198,0.429652,0.453179
17,mlp_experience_replay_confidently_correct_memo...,0.167709,0.429055,0.422260,0.466558,0.437611,0.466160
18,mlp_experience_replay_hard_example_mining_RR_0.2,0.056223,0.221334,0.426822,0.455262,0.423364,0.474515
19,mlp_experience_replay_hard_example_mining_RR_0.3,0.088078,0.336446,0.415755,0.463620,0.431548,0.478690
20,mlp_experience_replay_hard_example_mining_RR_0.4,0.082229,0.231078,0.419475,0.432621,0.427389,0.471639
21,mlp_experience_replay_hard_example_mining_RR_0.5,0.059818,0.244846,0.425019,0.463890,0.431746,0.459895
22,mlp_experience_replay_uncertainity_prioritizat...,0.172727,0.434311,0.425061,0.465918,0.445364,0.446195
23,mlp_experience_replay_uncertainity_prioritizat...,0.194138,0.439962,0.433673,0.472891,0.456998,0.463931
24,mlp_misclassification_buffer_RR_0.3,0.044570,0.390983,0.388780,0.431391,0.403180,0.472778
25,neighbours,0.103237,0.170805,0.109106,0.120809,0.101794,0.153380
26,prevyears_monthly_features,0.092160,0.356850,0.356100,0.392861,0.383586,0.392930
27,prevyears_monthly_features_experience_replay,0.085825,0.332732,0.351281,0.396565,0.372886,0.397788
28,prevyears_monthly_features_incremental_scaler,0.084545,0.332065,0.354247,0.403411,0.370796,0.401422
29,prevyears_monthly_features_incremental_scaler_...,0.105397,0.342351,0.339520,0.375780,0.358094,0.376471
30,sgd_experience_replay_RR_0.2,0.099419,0.345718,0.349169,0.384348,0.366297,0.381657
31,sgd_experience_replay_RR_0.3,0.103814,0.342252,0.343854,0.378050,0.361288,0.370231
32,sgd_experience_replay_RR_0.4,0.102821,0.343551,0.343381,0.375987,0.355479,0.369755
33,sgd_experience_replay_RR_0.5,0.106972,0.352264,0.340746,0.382089,0.363753,0.378073
34,prevyears_monthly_features_rbf,0.016984,0.019534,0.018757,0.029362,0.016832,0.029462

Saved: eval_outputs\unified_eval\summary_matrices\metric_matrix_prior_years_model_2022_pr_auc.csv

Skipped families (missing/invalid outputs):
 - huber: combined csv not found
 - mlp_prevyears_monthly_features_incremental_scaler_experience_replay: combined csv not found
 - mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.2_PR_0.10: combined csv not found
 - mlp_prevyears_monthly_features_incremental_scaler_experience_replay_RR_0.5_PR_0.10: combined csv not found
 - mlp_prevyears_monthly_features_incremental_scaler_experience_replay_uncertainity_prioritization_RR_0.2: combined csv not found
 - mlp_prevyears_monthly_features_incremental_scaler_experience_replay_uncertainity_prioritization_RR_0.5: combined csv not found

Summary matrix exports complete.
Output folder: eval_outputs\unified_eval\summary_matrices

                table_type  metric  row_count
0               cumulative      f1         35
1               cumulative  pr_auc         35
2    final_model_each_year      f1         27
3    final_model_each_year  pr_auc         27
4                next_year      f1         35
5                next_year  pr_auc         35
6                 own_year      f1         35
7                 own_year  pr_auc         35
8   prior_years_model_2017      f1         35
9   prior_years_model_2017  pr_auc         35
10  prior_years_model_2018      f1         35
11  prior_years_model_2018  pr_auc         35
12  prior_years_model_2019      f1         35
13  prior_years_model_2019  pr_auc         35
14  prior_years_model_2020      f1         35
15  prior_years_model_2020  pr_auc         35
16  prior_years_model_2021      f1         35
17  prior_years_model_2021  pr_auc         35
18  prior_years_model_2022      f1         35
19  prior_years_model_2022  pr_auc         35